### ISSUE TITLE
Error handling for sfpowerkit:package:valid

### ISSUE THREAD

**Issue by lmondigo** [Accenture/sfpowerkit#105]
Error on sfdx sfpowerkit:package:valid

Source was successfully converted to Metadata API format and written to the location: /home/vsts/work/1/s/temp_sfpowerkit/mdapi
ERROR running sfpowerkit:package:valid: existing.Package.types is not iterable

**Comment by azlam-abdulsalam** [comment]
Fixed in 1.18.7,
Thanks for raising the issue
