### ISSUE TITLE
Profile merge: "No full name on profile component"

### ISSUE THREAD

**Issue by asneyap** [Accenture/sfpowerkit#112]
Hi,

When running sfpowerkit:source:profile:merge, only saves information for profiles that were not previously part of the project folder. For those that exist and should merge the information, it throws a "No full name on profile componente" for each one when loading the chunks.

That error message comes from the ProfileWriter class.

The result lists include all added and merged profiles but the merged ones were not modified actually.

```
$ sfdx version
sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3

```

Regards

**Comment by asneyap** [comment]
Fixed in src/impl/source/profiles/profileMerge.ts, before ln 636, add:

`        profileObj.fullName = profileObjFromServer.fullName;
`
I can create a Pull Request if you give me access to the repo.

**Comment by azlam-abdulsalam** [comment]
Thank you for raising the issue. Wondering how it slip through. Will look into the test cases.

Assigning to @genoud  for a comprehensive review.

@asneyap  Would you be able to fork the repo and raise a PR?

**Comment by payensa-sf** [comment]
Hi,

I forked the project and created a PR to your master.

Thanks for your excellent work with this plugin.

Regards.

**Comment by azlam-abdulsalam** [comment]
Awesome, Thanks again

**Comment by genoud** [comment]
Hello @asneyap, @payensa-sf ,

Thank you for the raising the issue and for the fix. I just did a review.
