### ISSUE TITLE
ambiguous argument '0000000' when running project:diff command

### ISSUE THREAD

**Issue by sfdcale** [Accenture/sfpowerkit#115]
```
> rm -r deploy_folder && sfdx sfpowerkit:project:diff --output deploy_folder --revisionfrom 6b563c8 --revisionto HEAD
fatal: ambiguous argument '0000000': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I am on latest sfdx and plugin version.

**Comment by azlam-abdulsalam** [comment]
@sfdcale  n the revision from can you  pass the full sha id and observe whether the issue persists?

**Comment by sfdcale** [comment]
@azlam-abdulsalam  Still same result. 

Here is the command I tried.
```
> rm -rf deploy_folder && sfdx sfpowerkit:project:diff --output deploy_folder --revisionfrom 6b563c8e9034227c723706a3b322a90f0c131336 --revisionto HEAD
fatal: ambiguous argument '0000000': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by sfdcale** [comment]
@azlam-abdulsalam  In spite of this error, diff is produced and written to the output folder but I haven't checked if the diff files are accurate.

Thanks again for creating this awesome plugin.

**Comment by azlam-abdulsalam** [comment]
@sfdcale  Looks like its a message thrown by the git diff command which sfpowerkit uses. Can you confirm your directory is all good

**Comment by sfdcale** [comment]
@azlam-abdulsalam  I haven't seen this message lately and I haven't been able to reproduce. We can close this issue.

**Comment by azlam-abdulsalam** [comment]
@sfdcale  thanks for the update

**Comment by blaskowski94** [comment]
Just wanted to callout I am still seeing this error when running the diff command. Diff still appears to be generated correctly, not sure exactly why it's showing up.

**Comment by genoud** [comment]
Hello @blaskowski94 . Which version of sfpowerkit are you using? I recently fix an issue on the diff command that was occurring when files was renamed. https://github.com/Accenture/sfpowerkit/pull/210. 
Could this be the cause of this issue? Can you check if the git diff command is showing renamed files?
