### ISSUE TITLE
Update email and image URL of email templates so that different community urls per env can be handled

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#128]
Create a sfpowerkit:org:emailtemplate:update to support handling community links changes for static resources on  email  templates which change per environment

**Comment by azlam-abdulsalam** [comment]
I am thinking may be better we create a full fledged templating option which can replace  a string anywhere, say something that starts with a special characters like %sfpowerkit_email_url%

**Comment by azlamsalam** [comment]
Closing this, as we await templating as a native feature in the CLI
