### ISSUE TITLE
Metadata retreivals are not displaying proper error message, if the target org doesnt contain the requested metadata

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#131]
This issue impatcts all retrieval commands, the command pull downs a zip file with the requested package.xml but it wont contain the requested metadata, so we have to checkout and extract the code and then warn the user appropriately or better update to utilize conn.metadata.readsync

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  are we planning any further work on this segment?

**Comment by manisfdcsfdx** [comment]
@azlam-abdulsalam need more details on it.
