### ISSUE TITLE
Unable to install SFPowerkit

### ISSUE THREAD

**Issue by skhare25** [Accenture/sfpowerkit#137]
**Describe the bug**

Issues while installing sfpowerkit plugin in Windows 10 machine. SFDX CLI is already installed in the system.

**To Reproduce**

From VS code terminal ,or command line , Entering below mentioned command

	
sfdx plugins:install sfpowerkit

**Expected behavior**

Sfpowerkit need to install properly.

**Screenshots**

Not applicable. Error message is mentioned below:

 

sfdx plugins:install sfpowerkit This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y Finished digital signature check. Error: EISDIR: illegal operation on a directory, read at Object.readSync (fs.js:493:3) at tryReadSync (fs.js:332:20) at Object.readFileSync (fs.js:369:19) at onUnexpectedError (C:\Users\XXXXXX\AppData\Local\sfdx\client\7.27.0-714f62f9c1\node_modules\yarn\lib\cli.js:91833:100) at C:\Users\XXXXXX\AppData\Local\sfdx\client\7.27.0-714f62f9c1\node_modules\yarn\lib\cli.js:91936:9 Installing plugin sfpowerkit... ! Error: yarn add sfpowerkit@latest --non-interactive --mutex=file:C:/Users/XXXXXX/AppData/Local/sfdx/yarn.lock --preferred-cache-folder=C:/Users/XXXXXXX/AppData/Local/sfdx/yarn --check-files exited with code 1 at ChildProcess.forked.on (C:/Users/XXXXXXX/AppData/Local/sfdx/client/7.27.0-714f62f9c1/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)"

 

**Desktop (please complete the following information):**

 

- OS: [e.g. iOS]  : Windows 10 

- Version of sfowerkit[e.g. 22] : First time installation.

- Salesforce Org Version [ In case of pre-release window ] : Winter’20

 

**Additional context**

This problem is somehow occurring with one machine, although the configurations are same as that of other machines.

**Comment by azlam-abdulsalam** [comment]
Can you update to the latest sfdx cli version and try again?

**Comment by skhare25** [comment]
Already tried with latest cli version still faced same issue

**Comment by skhare25** [comment]
Tried again by uninstalling Visual Studio and CLI, after insallation it worked. Thanks for the help
