### ISSUE TITLE
Profile reconcile not removing items against the destination org.

### ISSUE THREAD

**Issue by jhawk-kar** [Accenture/sfpowerkit#139]
Using sfpowerkit 1.25.3-0 (alpha), the profile reconcile command does not remove all items from the profile that are missing in the destination org.

Ran command to retrieve profile from a source
`$ sfdx sfpowerkit:source:profile:retrieve -n "ProfileName" -u sourceOrg`

Ran command to reconcile against the destination
`$ sfdx sfpowerkit:source:profile:reconcile -n "ProfileName" -u destinationOrg -d ./deployment/destination/force-app/profiles --loglevel=debug`

The destination org from the `-u`  parameter is missing several tabs, objects, classes, and pages from the source org.

Ran command to deploy the reconciled profile to the destination org
`$ sfdx force:source:deploy --sourcepath ./deployment/destination/force-app/profiles/ProfileName.profile-meta.xml -u destinationOrg`

Results in errors for profile referencing components missing from destination org.

Attached the output from the reconcile command with debug tracing.
[sfpowerkitlogs.txt](https://github.com/Accenture/sfpowerkit/files/3764387/sfpowerkitlogs.txt)

**Comment by genoud** [comment]
This does not seems to be a bug. the components that are kept in profile are components that are found in the project from which you ran the command.

The reconcile command look for component in the project before looking in the target org, assuming that profiles will be deployed together with project components.

**Comment by azlam-abdulsalam** [comment]
@jhawk-kar  Please find the alpha version 1.25.3.2 which has a minor fix as well,  Can  you update it and send in your feedack

**Comment by jhawk-kar** [comment]
> @jhawk-kar Please find the alpha version 1.25.3.2 which has a minor fix as well, Can you update it and send in your feedack

@azlam-abdulsalam Hit an error `Maximum SOQL offset allowed in 2000`.  The total retrieve size was 3348, and the offset hit 2200 when the error surfaced.  Can the query been run in chunks of 2000 instead of 200 to reduce the number of offsets required?  

> This does not seems to be a bug. the components that are kept in profile are components that are found in the project from which you ran the command.
> 
> The reconcile command look for component in the project before looking in the target org, assuming that profiles will be deployed together with project components.

@genoud When I read the documentation for the reconcile command, it made it seem as if it were going to look to reconcile against either the org, or the package source.  So, if you choose to specify an org to reconcile against, it will actually do both?

**Comment by genoud** [comment]
> hen I read the documentation for the reconcile command, it made it seem as if it were going to look to reconcile against either the org, or the package source. So, if you choose to specify an org to reconcile against, it will actually do both?
@jhawk-kar Yes, when you specified an org, the components are checked first in source then in the org if not found. The sourceOnly flag allow to check only in the source. May be we need to make it clearer in the doc.

**Comment by azlam-abdulsalam** [comment]
@jhawk-kar Addressed this in the new alpha version, 1.25.3-4, Its being reviewed.. Please give it a spin

**Comment by jhawk-kar** [comment]
I think we have a winner.  I was able to successfully reconcile against the target org and the profile deployed successfully to that org.  I'll keep working through different testing scenarios, as I think this command really helps out for our needs, but we are all set for now.  Thanks for your diligence in finding a solution.

**Comment by azlam-abdulsalam** [comment]
Thanks again for your contribution, We will be merging this to the release/master branches once we are done with some reviews.
Please do switch to the latest stable version once it is done.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
