### ISSUE TITLE
sfpowerkit:project:diff is ignoring Added files

### ISSUE THREAD

**Issue by sfdcale** [Accenture/sfpowerkit#146]
![Screen Shot 2019-10-29 at 11 06 25 AM](https://user-images.githubusercontent.com/11079913/67795933-55719680-fa3c-11e9-99f8-a78934d5cbc5.png)

As we can see in the screenshot, it is preparing output directory with only Modified files and ignoring Added files.

sfpowerkit 1.24.2
macOS 10.14.5

**Comment by azlam-abdulsalam** [comment]
@sfdcale  Can you confirm whether the added files are actually present in the output directory, we have noted a bug with the logging, but files are actually created.
Just confirming if thats the case

@uvaisfdc fyi

**Comment by genoud** [comment]
I was able to reproduce the issue with following steps

1. Create a repo
2. add a class
3. commit
4. edit the class
5. commit again
6. delete the class
7. commit again
8. run the command `sfdx sfpowerkit:project:diff -d output -r HEAD~2 -t HEAD~1`

The command copy files from the file system and if a file listed in the git diff is not present in the folder, you may have this issue. 

We will improve the command to fetch file from git instead.

**Comment by azlam-abdulsalam** [comment]
@sfdcale Thanks, Is @genoud 's understanding and the steps to reproduce it are correct?

**Comment by sfdcale** [comment]
![Kapture 2019-10-30 at 13 25 47](https://user-images.githubusercontent.com/11079913/67896083-e28a1d80-fb18-11e9-8b94-3fce39621274.gif)

Here is the Gif showing it.

`diff` command is depending on actual files to be there locally. If files are not there locally, it is not creating anything in output folder. 
It was just coincidental that in my original issue, it did not create Added files but this can happen for Modified files also.

cc: @azlam-abdulsalam @genoud

**Comment by dineshpsalm** [comment]
team, 
My first commit 
![git1](https://user-images.githubusercontent.com/59183645/87332576-ab875b00-c533-11ea-90b1-ea1365f80578.png)
This is my second commit
![git 2](https://user-images.githubusercontent.com/59183645/87332574-aaeec480-c533-11ea-88b0-7cf299d91183.png)
Sfdx power kit diff command output. 
![git 3](https://user-images.githubusercontent.com/59183645/87332575-aaeec480-c533-11ea-9fdf-c207d9d94446.png)

Question:
I hope this powerkit compare the changes on one previous commit and recent commit and use recent commit changes on org. if that is the case, 
then 1. why should it listing out pmdtest.cls-meta.xml,  and Territory_Zip_Code__c-Territory Zip Code Layout.layout-meta.xml in my diff.json file ? 
2. CreateContactController.xml file is not modified by me on second time ,then how come it added in my diff.json file ? 
3. My newly added demofile.xml also not listed in sfdx power kit diff? why 
4. how to check my powerkit version number in CLI ? - Pls note i installed recent stable version using "sfdx plugins:install sfpowerkit" 

Can anyone help me or direct me to right page.
