### ISSUE TITLE
Can't deactivate standard scratch org matching rules

### ISSUE THREAD

**Issue by thvd** [Accenture/sfpowerkit#149]
**Describe the bug**
On a scratch there are 3 default matching rules. But you cannot deactivate them using the `sfpowerkit:org:matchingrule:deactivate` command.

**To Reproduce**

1. `sfdx sfpowerkit:org:matchingrule:deactivate -n Account`

**Expected behavior**
Expected that the default Account matching rule is deactivated. But it isn't.

**Comment by azlam-abdulsalam** [comment]
@thvd  Do you have any duplicate rules on Account?  this should be deactivated before deactivating matching rules

**Comment by thvd** [comment]
The duplicate rules are all deactivated:
![image](https://user-images.githubusercontent.com/973711/67930639-7a8f1200-fbc0-11e9-9cab-e37c1744dbfe.png)

The Account matching rule is active: 
![image](https://user-images.githubusercontent.com/973711/67930657-88dd2e00-fbc0-11e9-8cab-f9f94d0d7fc6.png)

And when i run: 
```bash
sfdx sfpowerkit:org:matchingrule:deactivate -n Account
```

The result is:
```
Polling for Retrieval Status
Retrieved Matching Rule  for Object : Account
Preparing Deactivation
ERROR running sfpowerkit:org:matchingrule:deactivate:  Cannot set property 'ruleStatus' of undefined

```

**Comment by azlam-abdulsalam** [comment]
Standard Rules cannot be deactivated using the command, as the metadata api do not support. Will fix the readme and error in the next release

The approach is to use custom duplicate rule and custom matching rules, deploy all of them as inactive, then utilize the commands  to activate once they are deployed

**Comment by thvd** [comment]
@azlam-abdulsalam good to know, so there is no way to disable the standard rules with the API. That's disappointing. 
Thanks for the quick responses anyway.

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  Can you investigate whether this behaviour changed in v47? and add the details to the readme

**Comment by azlam-abdulsalam** [comment]
@thvd looks like a candidate for puppetteer , will enhance this command to support this in subsequent release

**Comment by qswh** [comment]
It would be good to turn off all those standard rules as it's not supposed to be used. It's more like a guided template to show the user how to configure it.
