### ISSUE TITLE
Strange issue with package:dependencies:install

### ISSUE THREAD

**Issue by hotcher2** [Accenture/sfpowerkit#15]
I am having an issue with one of my packages using a bash scripts that calls sfpowerkit:package:dependencies:install -k "1: 2:$KEY 3:$KEY" installing 3 dependencies for one of my unlocked packages.  The error says the InstallationKey is invalid for the 2nd package that attempts to be installed.  For a different unlocked package I have, these 3 dependencies install correctly with the plugin and I have never had any issues .   I've carefully reviewed my sfdx-project.json file (comparing it to the package that I'm not having any issues with) and  observed nothing wrong. 

So I decided this would be a good time to dive into learning how cli plugins work and maybe help find and fix an issue. I cloned the source and built the plugin on my local machine leaving it uninstalled and unlinked.  I added some logging statements to the install.ts command to hopefully learn more of what was causing the issue.  What happened was not what I expected.  The error never occurred and the command worked perfectly 4 times in a row when running from within the bash script.  Went back to to trying the installed plugin version and received the error again.

I've verified that both the installed version and the local unlinked version (using bin/run) are both the same - 1.9.28.  I'm really at a loss for what is going on and how to continue troubleshooting.

At this point I have no idea if it is a problem with the plugin or something in my environment.  One theory I had was maybe something is timing out.  I get frequent query timeout errors with the plugin trying to get the list of versions of packages.  Also, the first dependency that gets installed is the Pardot managed package which takes a long time to install.  Perhaps something is going on there and the plugin is "losing" the installationkey values after a period of time.  Again, I didn't see the issue with the local unlinked version.

Anyway, thought i'd report the issue in case someone knows of a possible solution, or if others are having the same problem.

Environment:
sfdx-cli 7.13.0
node 11.13 (via nvm)
yarn 1.16
macOS Mojave 10.14.5

**Comment by azlam-abdulsalam** [comment]
Thanks for raising the issue.
Interesting , is it possible to share the sfdx-project.json?  I have been seeing some timeouts.when trying to.query the package version recently, but not this.

**Comment by hotcher2** [comment]
Sure, I've replaced real package names with fakes, but this is the actual structure:

```json
{
    "packageDirectories": [
        {
            "path": "./pkgabc",
            "package": "acme-pkgabc",
            "versionName": "ver 1.2",
            "versionNumber": "1.2.0.NEXT",
            "default": true,
            "dependencies": [
                {
                    "package": "Pardot@4.20.0.1"
                },
                {
                    "package": "acme-core",
                    "versionNumber": "1.2.0.LATEST"
                },
                {
                    "package": "acme-common",
                    "versionNumber": "1.2.0.LATEST"
                }
            ],
            "features": [
                "ServiceCloud",
                "StateAndCountryPicklist",
                "Pardot"
            ]
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "46.0",
    "packageAliases": {
        "Pardot@4.20.0.1": "04t1W000000HbiXQAS",
        "acme-core": "corepkgid",
        "acme-core@1.2.0-1": "coreverid",
        "acme-common": "commonpkgid",
        "acme-common@1.2.0-7": "commonverid",
        "acme-pkgabc": "pkgabcpkgid",
        "acme-pkgabc@1.2.0-2": "pkgabcverid"
    }
}
```

**Comment by azlam-abdulsalam** [comment]
Thanks, in your scenario does acme-core and acme-commons utilise an installation key as well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hotcher2** [comment]
Yes, core and common have installation keys but Pardot does not.  My bash script call to sfpowerkit is as follows where $KEY is passed in:

```bash
sfdx sfpowerkit:package:dependencies:install -r -k "1: 2:$KEY 3:$KEY" --wait 10
```

**Comment by azlam-abdulsalam** [comment]
Created an issue AB#31 to track this.

**Comment by hotcher2** [comment]
Ok, I feel like an idiot.  I believe the issue was being caused by an error in a bash script.  I apologize for the inconvenience but thank you for taking the time to respond so quickly!
