### ISSUE TITLE
project:diff is just copying the current copy of local file to output directory and ignoring the actual changes between commits

### ISSUE THREAD

**Issue by sfdcale** [Accenture/sfpowerkit#152]
![Kapture 2019-10-30 at 13 35 39](https://user-images.githubusercontent.com/11079913/67896809-5b3da980-fb1a-11e9-80b5-a07692afd253.gif)

Here are the steps:

1. Take any file, make some changes and do a commit. lets call this **commit 1**
2. Make more changes to the same file and do another commit. lets call this **commit 2**
3. Make more changes to the same file and do another commit. lets call this **commit 3**
4. Run project:diff command between **commit 2** and **commit 1** and the output directory will have changes from **Commit 3** also but it should have changes only up to **Commit 2**

**Comment by azlam-abdulsalam** [comment]
@sfdcale  This is same as the issue #146 , which will be fixed in the next release

**Comment by azlam-abdulsalam** [comment]
@sfdcale , @genoud  have just finished a Pull Request fixing this and undergoing review and testing.  Would you be able to install the alpha build using the command
sfdx plugins:install sfpowerkit@alpha and test the different combinations and provide feedback

**Comment by sfdcale** [comment]
@azlam-abdulsalam  @genoud verified with alpha version and it looks good. Thanks for fixing it quickly.
