### ISSUE TITLE
Org: manifest:build fails in a new org

### ISSUE THREAD

**Issue by azlamsalam** [Accenture/sfpowerkit#183]
sfpowerkit:org: manifest:build fails to execute when applied on a new org with no deployments so far. It also fails if an unlocked package is the only deployed component

**To Reproduce**

1. sfdx sfpowerkit:org: manifest:build against a new org
2. It will throw an exception
3. Install an unlocked package
4. Run the command with -x option
5. It will fail again

**Expected behaviour

Its should throw an accurate error

**Comment by genoud** [comment]
I was not able to reproduce this issue.
 I created a new Developer Org and run the command and did not get any error.
I also created an unlocked package and install in the org and did not get any issue.

**Comment by genoud** [comment]
@azlam-abdulsalam Is this still happening?

**Comment by azlam-abdulsalam** [comment]
Closing this issue  as its not reproduceable
