### ISSUE TITLE
add sfpowerkit:source:style:format to format apex (and others) source files with prettier

### ISSUE THREAD

**Issue by rody** [Accenture/sfpowerkit#188]
**Is your feature request related to a problem? Please describe.**

Now that [Prettier](https://prettier.io/) is the [official formatting tool for the Salesforce VSCode extensions](https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/), it would be useful to have an sfdx command to format Apex code.
The support for Apex in prettier is provided by [prettier-apex-plugin](https://github.com/dangmai/prettier-plugin-apex).

**Describe the solution you'd like**

Sfpowerkit could include commands to check and format Apex source code (and maybe other source files as well). We could have the following new commands:

 - `sfpowerkit:source:style:check` to check if the files are in the correct format
 - `sfpowerkit:source:style:format` to format the source files

Each command should be able to be executed on one or multiple files, as well as on the entire code base.

**Describe alternatives you've considered**

My current alternative is to create a fake NPM project to add the prettier dependencies and add custom npm scripts to format the source code. Whilst it works perfectly, it requires extra setup for each project and forces developers to use Node-related tools directly instead of the well-know `sfdx`.

**Comment by rody** [comment]
Here are the step I use when configuring prettier on a sfdx project:

1. Initialise a NPN project in the sfdx project
`npm init`

2. install prettier and its dependencies
`npm install --save-dev prettier prettier-plugin-apex`

3. edit the standard `.prettierrc`file generated during `sfdx force:project:create`:
```json
{
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    },
    {
      "files": "*.{cls,trigger}",
      "options": {
        "parser": "apex",
        "tabWidth": 4
      }
    }
  ]
}
```
(I set the tabWidth=4 because the developer console is set this way).

4. add scripts to `package.json`
```
 (...)
  "scripts": {
    "prettier:check": "prettier --check **/*",
    "prettier:lint": "prettier --write **/*"
  },
(...)
```
(ideally, the '**/*' should be replaced by the package directories).

5. commit `package.json`, `package.lock` and `.prettierrc` to Git.

In sfpowerkit prettier and the apex plugin should be declared as dependencies so we can skip the whole NPN project creation.(

Prettier can be integrated either directly trough its [API](https://prettier.io/docs/en/api.html) or with the [CLI](https://prettier.io/docs/en/cli.html).

**Comment by azlam-abdulsalam** [comment]
Closing this as, its a lower priority of now.
