### ISSUE TITLE
JSON Output for diff commands

### ISSUE THREAD

**Issue by azlamsalam** [Accenture/sfpowerkit#190]
**Is your feature request related to a problem? Please describe.**
It would be helpful if the current diff commands produce a JSON result file that encompass the findings of the diff tool along with the diff run.  One use case of this, it  could be utilized in a CI/CD run to check for compliance 

**Describe the solution you'd like**
An output parameter to generate the result of the diff command as in JSON file should be helpful

**Describe alternatives you've considered**
None - try running twice with --json to generate the json output. but bit of a drag

**Comment by genoud** [comment]
Already done. Closing this issue
