### ISSUE TITLE
sfdx sfpowerkit:project:diff between 2 commits - profiles related

### ISSUE THREAD

**Issue by maazinbeig** [Accenture/sfpowerkit#191]
**Describe the bug**
Incorrect diff generated for profiles when using "sfpowerkit:project:diff" between 2 commits that contain changes on an object, apex class and profile.

The correct profiles get detected but generated profile file did not contain the "CustomMetadataTypeAccess" change made and an additional single tag: **< fullName/ >** gets created, throwing the below error while deploying:

" fullName specified in file does not match file name"

**To Reproduce**

1. sfdx sfpowerkit:project:diff --revisionfrom **commit1** --revisionto **commit2** --output **folder name**
2. Add **CustomMetadataTypeAccess** (Released with API 47.0) to profile, in addition to any other change in the profile e.g. making field editable/readable.
3. Change an object file, add description to a field.
4. Upon generating diff, the profile file is incorrect.

**Expected behavior**
Profile should contain **CustomMetadataTypeAccess** and **FieldPermission**

**Screenshots**
Profile retrieved:
![image](https://user-images.githubusercontent.com/60119360/72772083-2a6f9b00-3c57-11ea-9412-42c1c3495c11.png)

**Desktop (please complete the following information):**

- OS: Microsoft Window
- Version of sfowerkit - latest
- Salesforce Org Version - Preview instance, Winter 20'

Appreciate any help with this.

Thanks

**Comment by blaskowski94** [comment]
I believe CustomSettingAccess has the same issue. It was also added in 47.0.

I worked around the fullName issue by adding the fullName tag as the first line of every profile in our metadata. For example:

    <fullName>Profile Name</fullName>

**Comment by azlamsalam** [comment]
@genoud Do we have to update our profile: reconcile or retrieve for these as well?

**Comment by genoud** [comment]
We already updated the profile reconcile and merge commands to take into consideration flowAccess and customMetadataAccess. We will need to add customSettingAccess to those commands. I will do that.
The retrieve command should normally work. But I tested and only flowAccess get retrieved even if set to false. CustomMetadata and customSetting accesses are retrieved only if set to true.

**Comment by genoud** [comment]
We will need to add this also to permission set diff.
