### ISSUE TITLE
ERROR running sfpowerkit:project:diff:  Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by austinmyer** [Accenture/sfpowerkit#200]
This is happening with Platform Event

**Comment by azlam-abdulsalam** [comment]
@austinmyer  I presume from the description,  you are not able to include any Platform Events?

**Comment by genoud** [comment]
@austinmyer can you give more input on this issue and how to reproduce it?
Thanks

**Comment by austinmyer** [comment]
Sory, my bad, its not the platform event, the PR for which we were doing the diff validation had the API name change. Can we have a look if diff is good with file name changes

**Comment by azlamsalam** [comment]
@austinmyer Can you provide a step by step instructions to reproduce thi

**Comment by austinmyer** [comment]
Describe the bug
Cannot generate diff when some files are renamed.

To Reproduce
Steps to reproduce the behavior:

Rename a file.
Add and commit renamed file.
Generate diff.
Expected behavior
Renamed file should be included in diff.
