### ISSUE TITLE
Error on running diff when files are renamed

### ISSUE THREAD

**Issue by lrmondigo** [Accenture/sfpowerkit#205]
**Describe the bug**
Cannot generate diff when some files are renamed.

**To Reproduce**

1. Rename a file.
2. Add and commit renamed file.
3. Generate diff.

**Expected behavior**
Renamed file should be included in diff.

**Screenshots**
![image](https://user-images.githubusercontent.com/48669617/73515144-344f8600-442f-11ea-89ee-a4089b5e98f4.png)

**Comment by manisfdcsfdx** [comment]
@lrmondigo this is duplicate issue #200

**Comment by lrmondigo** [comment]
> @lrmondigo this is duplicate issue #200

Closing as they have seemed to identify cause of the issue as well.
