### ISSUE TITLE
Matching rule deactivation with JSON output has extra string at the end.

### ISSUE THREAD

**Issue by lmondigo** [Accenture/sfpowerkit#228]
**Describe the bug**
Unnecessary string on --json result when deactivating matching rules.

**To Reproduce**
1. Create a matching rule that will fail on deactivation.
2. Deactivate matching rule using sfpowerkit and add --json to the command.

**Expected behavior**
Only JSON format should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/16076249/77242292-e9d0d580-6c37-11ea-8254-d2ae383f3c53.png)

**Additional context**
Trying to handle errors when running the command from a shell script. Normal behavior is print error on output when ran from a shell script. I want to fail build when the command fails, hence parsing the JSON output.

**Comment by lmondigo** [comment]
@azlam-abdulsalam @manisfdcsfdx have you checked this yet?

**Comment by manisfdcsfdx** [comment]
@lmondigo issue addressed in beta version. test the command with beta command.
