### ISSUE TITLE
 sfpowerkit:auth:login failed if use specific symbols in the password 

### ISSUE THREAD

**Issue by Panineduard** [Accenture/sfpowerkit#244]
**Describe the bug**
If you try to login with specific symbols in the password the console returns the error message 
**is not recognized as an internal or external command**

**To Reproduce**

**[@>|]**
1. sfdx sfpowerkit:auth:login -u test@dev.org -p 1234|HeL>o@ -s 1231546  -r https://login.salesforce.com -a dev-org

**Expected behavior**
The system should log in to the environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/12416215/79328572-f1298d00-7f1e-11ea-8278-9e198a95ecd7.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Version of sfowerkit[v1.43.3]

**Comment by manisfdcsfdx** [comment]
@Panineduard can try passing the password inside single quote as a string '1234|HeL>o@'

**Comment by Panineduard** [comment]
Hello @manisfdcsfdx 

I already did it. It doesn't help. 
![image](https://user-images.githubusercontent.com/12416215/80078219-42590280-8557-11ea-866d-9afac7acf510.png)

**Comment by manisfdcsfdx** [comment]
@Panineduard thanks for the confirmation. We will check the issue in more detail.

**Comment by aly76** [comment]
Thank you for the update @Panineduard . I was able to resolve this issue on my Windows machine by encapsulating the password with double quotes `-p "1234|HeL>o@"`.

Could you check if this also fixes the problem on your end? 

Cheers

**Comment by azlam-abdulsalam** [comment]
Thanks @aly76 for confirming. closing the issue

**Comment by Panineduard** [comment]
Thanks. It helps in the Azure DevOps plugin too.
