### ISSUE TITLE
Dependency CLI

### ISSUE THREAD

**Issue by manisfdcsfdx** [Accenture/sfpowerkit#258]
**Is your feature request related to a problem? Please describe.**
Often it is important to understand dependency structure of a specific component or a package to untangle the metadata or to understand the impact on dependents before making any modification on a certain components or a metadata

**Describe the solution you'd like**
create below commands to get dependency tree 

*dependency for package*
sfdx sfpowerkit:dependency:tree:package -u sandbox -n core
sfdx sfpowerkit:dependency:tree:package -u sandbox -n 04txxxxxxxxxx

*dependency for source*
sfdx sfpowerkit:dependency:tree -u sanbox -m ApexClass,ApexTrigger
sfdx sfpowerkit:dependency:tree -u sanbox -m ApexClass:myclass,ApexTrigger:myTrigger
sfdx sfpowerkit:dependency:tree -u sanbox -p src/main/default/objects/Account
sfdx sfpowerkit:dependency:tree -u sanbox -x package.xml

**Describe alternatives you've considered**
run multiple SOQL in salesforce.

**Additional context**
Dependency API is a salesforce Beta feature from winter 20. https://releasenotes.docs.salesforce.com/en-us/winter20/release-notes/rn_api_metadatacomponentdependency_beta.htm

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx
-   Can you elaborate on how the metadata id is resolved into qualified names? 
- Whats the proposed output formats?
- Why should we have a variant when depenedency cli exists

**Comment by azlam-abdulsalam** [comment]
A early version of the command  is now merged, it features a depenedency cli which can produce a json output of the depenendencies.

**Comment by azlam-abdulsalam** [comment]
Need this for a source package
