### ISSUE TITLE
Scratch Org Pooling

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#259]
**Is your feature request related to a problem? Please describe.**
Salesforce snapshot is delayed by couple of releases making scratch org based PR an incredibly painful affair after the project has grown into some size. It is also difficult when large managed packages are involved. We need an interim solution that can help us alleviate some of the pain

**Describe the solution you'd like**
I propose we add three new commands to sfpowerkit under the scratchorg namespace

*pool:create*

  - Create a pool of scratch orgs  for a tag or for a list of users as defined in a json based schema identified by a tag.
 -  The default option is to create a pool of scratch orgs identifiable by a tag.
  - When user mode is selected, Users need to be allocated ScratchOrgs  based on  the min/max/priority  capacity mentioned in the pool config. The order of allocation is provide max capacity to everyone if available or else allocate minimum to everyone and then allocate remaining based on priority in round robin manner. The command will try to allocate upto the capacity depending on the availability at any given point.
  - The command will be executed from a project directory
  - The command should support executing a bash/batch script on each created scratch org in the pool on the basis of the platform the command is run.
  - ScratchOrgs should be generated with admin email set to the user mentioned in the schema or the user who is creating the pool. This will allow the pool user to validate to the scratch org using their own email id and utilizing a web auth. If ip ranges are relaxed then this is not required
   - The scripts should be executed parallelly on each scratch org in the pool to save the overall time.
  -  Update ScratchOrg info object with details such as pooltag__c,, password__c, Allocation_status__c,  maintain a record only if the installation of dependencies are succesfull 
   ~~- This command can only be executed by a user who has a ProvisionPool permissionset. ( Permission set should be part of unlocked package)~~

*pool:fetch*
   - Fetch a free  Scratch Org from the created pool (identified by the tag)
   -  The command should update the status of the fetched Scratch Org updating IsAllocated__c to true. 
   -  The command should retry till a user gets a valid scratchorg (if the fetch command is not able to update the status, it will try fetching an alternate one from the pool) till it gets a scratchorg for specific user / tag

*pool: hydrate*
   - Cleanup all the scratchorg created by the pool owner (identified by a tag) with ability to delete only unused or both

**Describe alternatives you've considered**
- Only do pooling for CI user, which is simpler

**Comment by jacobpeterson2012** [comment]
Nice! Should we think about adding some sort of tagging or version to the SO build? For example, in our pool we have to expire them when we upgrade Vlocity and time this with changes in our repo.  This can be an issue if we want to run CI on a branch but our SO's are at a higher level.

**Comment by azlam-abdulsalam** [comment]
Thats a good idea, do you reckon a single tat would be suffice for a specific user?

**Comment by jacobpeterson2012** [comment]
I'm thinking the build should:
- allow a "tag" to be associated with the SO record.  
- in the fetch you can pass in a "tag" as a filter to allocate a SO.

**Comment by azlam-abdulsalam** [comment]
@jacobpeterson2012 This is the schema I have been thinking, accommodating tag is going to be hard

`{
  "pool": {
    "default_expiry": 1,
    "config_file_path": "config/project-scratch-def.json",
    "script_file_path": "scripts/so_script.sh"
    
  },
  "poolUsers": [
    {
      "max_allocation": 2,
      "min_allocation": 1,
      "username": "emailid",
      "expiry": 7,
      "priority":2
    }
]}`

**Comment by rody** [comment]
Is the pool going to be initialized only with the dependencies of the current project, or are we going with something more complex in the script?
If we limit ourselves to installing dependencies, we don't need a separate script file. The rest (data upload, ...) can be done through a CI that can poll new scratch orgs and do some specific work.

**Comment by azlam-abdulsalam** [comment]
the script doesnt limit anything it passes in the Scratch Org username and the DevHub username

**Comment by azlam-abdulsalam** [comment]
After a long conversation with @rody  and @jacobpeterson2012  there are couple of changes in the spec. i have updated the initial proposal
