### ISSUE TITLE
Delta package task does not work for branches with '/' in their names

### ISSUE THREAD

**Issue by Majd-Soufan** [Accenture/sfpowerkit#278]
**Describe the bug**
The delta package task in ADO does not work when the branch name has '/' in it. Some company follow naming conventions when it comes to git branch naming. I normally name my release branch 'release/46v2'. The task runs the npx sfdx sfpowerkit:project:diff command. 
The error showing is : 

##[error]Unhandled: Command failed: npx sfdx sfpowerkit:project:diff -t  bc65ed514d5fe289d90d9a87db3e8a428946de34 -r  $(git rev-list -n 2 origin/$BUILD_SOURCEBRANCHNAME | tail -1 ) -x -d  my_src_delta
fatal: ambiguous argument ‘origin/46v2’: unknown revision or path not in the working tree.
Use ‘--’ to separate paths from revisions, like this:
I think is is more of a git issue, but we fixed it with changing the naming convention into ‘release-46v2’

I think the command is skipping the first part of the branch name due to the '/' in the name. This could be fixed by changing the name e.g. replacing '/' with '-'. However, I want to know if we can escape the '/' in some way.

**Comment by genoud** [comment]
Hello,

I was not able to reproduce this issue.

![image](https://user-images.githubusercontent.com/10148667/84460870-05e18300-ac39-11ea-99e5-3dccc7896555.png)

Can you reproduce that on you pc and provide more logs?
Thanks

**Comment by Majd-Soufan** [comment]
Try to run the delta package on branch that has '/' in its name, like 'feature/2341'
The delta package will only take the '2341' part of the branch name and ignore the rest @genoud

**Comment by genoud** [comment]
Can you run the command with trace flag and provide logs?

**Comment by Majd-Soufan** [comment]
I am trying to use the delta between 2 commits on a branch called "hotfix/2324". Here are the error logs:

    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --[no-]object-names
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all


##[error]Exit with error code: 1
Async Command Start: Update Build Number
Update build number to 20200701.1 for build 165403
Async Command End: Update Build Number
Finishing: Create Delta Package based on two commits

**Comment by Majd-Soufan** [comment]
> Can you run the command with trace flag and provide logs?

I am trying to use the delta between 2 commits on a branch called "hotfix/2324". Here are the error logs:

fatal: ambiguous argument 'origin/2324': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git [...] -- [...]'

ERROR running sfpowerkit:project:diff: usage: git rev-list [OPTION] ... [ -- paths... ]
limiting output:
--max-count=
--max-age=
--min-age=
--sparse
--no-merges
--min-parents=
--no-min-parents
--max-parents=
--no-max-parents
--remove-empty
--all
--branches
--tags
--remotes
--stdin
--quiet
ordering output:
--topo-order
--date-order
--reverse
formatting output:
--parents
--children
--objects | --objects-edge
--unpacked
--header | --pretty
--[no-]object-names
--abbrev= | --no-abbrev
--abbrev-commit
--left-right
--count
special purpose:
--bisect
--bisect-vars
--bisect-all

##[error]Unhandled: Command failed: npx sfdx sfpowerkit:project:diff -t 9700d3b420ef853d3f031231cc8f8f22109852fa -r $(git rev-list -n 2 origin/$BUILD_SOURCEBRANCHNAME | tail -1 ) -x -d kar-sf-gdc_src_delta
fatal: ambiguous argument 'origin/2324': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git [...] -- [...]'
ERROR running sfpowerkit:project:diff: usage: git rev-list [OPTION] ... [ -- paths... ]
limiting output:
--max-count=
--max-age=
--min-age=
--sparse
--no-merges
--min-parents=
--no-min-parents
--max-parents=
--no-max-parents
--remove-empty
--all
--branches
--tags
--remotes
--stdin
--quiet
ordering output:
--topo-order
--date-order
--reverse
formatting output:
--parents
--children
--objects | --objects-edge
--unpacked
--header | --pretty
--[no-]object-names
--abbrev= | --no-abbrev
--abbrev-commit
--left-right
--count
special purpose:
--bisect
--bisect-vars
--bisect-all

##[error]Exit with error code: 1
Async Command Start: Update Build Number
Update build number to 20200701.1 for build 165403
Async Command End: Update Build Number
Finishing: Create Delta Package based on two commits

**Comment by genoud** [comment]
@Majd-Soufan it seems that your issue is with this subcommand and not sfpowerkit  `git rev-list -n 2 origin/$BUILD_SOURCEBRANCHNAME | tail -1`

**Comment by Majd-Soufan** [comment]
Thank you for pointing that out. This is a Git issue not sfpowerkit. I will close this issue
