### ISSUE TITLE
Validation Rules for Manifest for sfpowerkit:org:manifest:build command does not output

### ISSUE THREAD

**Issue by vuha-acn** [Accenture/sfpowerkit#279]
**Describe the bug**
Executing the sfpowerkit:org:manifest:build command, the expected result is there to be a "ValidationRule" type returned in the output file.

**For example:**

    <types>
        <members>Account.VR_Rule1</members>
        <name>ValidationRule</name>
    </types>

**To Reproduce**

Execute sfpowerkit:org:manifest:build against an org that has validation rules on objects. 

1. sfdx sfpowerkit:org:manifest:build

**Expected behavior**
Expected outputs of the following XML tags in the output file.

    <types>
        <members>Account.VR_Rule1</members>
        <name>ValidationRule</name>
    </types>

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.5
- Node Version
- Version of sfpowerkit 1.45.1
- Salesforce Org Version - Summer '20 Preview

**Additional context**
None

**Comment by genoud** [comment]
@vuha-acn I created a fix for this.I added a flag `--includechilds`, short hand `-c` to include child metadata in the generated` package.xml `file.
