### ISSUE TITLE
Retrieve profiles based on metadata in codebase

### ISSUE THREAD

**Issue by RobinWeymans** [Accenture/sfpowerkit#286]
Currently if you retrieve a profile, it has a lot of clutter. For example if you installed big apps from the app exchange. Fields permissions, app permissions of that app will be present in the retrieved profile and if you tried to deploy that profile to an environment without said app, it will obviously fail.

I currently have a solution but its written in bash. Thought this might be a good addition. If your tool can already do this, kindly let me know.

What I do to retrieve clean profiles is the following. 
I have my code base in source format that contains everything, specific to my project. First, I convert my codebase to mdapi with the force:source:convert command. This creates a big folder with a package.xml with only the things I have in my codebase. The package.xml is all I really need, so I discard all the generated mdapi files. Next, I do a mdapi retrieve with that package.xml. If my profiles were in my original codebase, the retrieved package will also contain them and ONLY contain permissions about things in my codebase.

A big disadvantage of this approach is that it can take a while, especially if you have a lot of metadata components. I've been doing this for quite some time now and it works great.

**Comment by azlam-abdulsalam** [comment]
@RobinWeymans  There is a similar functionality, however not as a single command, but a combination of these two commands will be effectively what you currently do.
`sfdx sfpowerkit:profile:retrieve` - To retrieve the profile with the full details from an org
`sfdx sfpowerkit:profile:reconcile -s` (Note the source flag, which basically reconciles a profile for only the metadata that you have in a given project directory). 
We use this command to split a profile across multiple repo's especially in a Scratchorg based modular development.

**Comment by RobinWeymans** [comment]
@azlam-abdulsalam Oh wow. Yeah that's exactly what I was looking for. I'm going to use that for sure.
Thanks!
