### ISSUE TITLE
profile:retrieve, profile:merge use incorrect indentation, causing full-file diff

### ISSUE THREAD

**Issue by jclark-dot-org** [Accenture/sfpowerkit#287]
**Describe the bug**
Given an existing git repo for an sfdx project, running `sfdx sfpowerkit:source:profile:retrieve -n "Profilename"` or `sfdx sfpowerkit:source:profile:merge -n "Profilename"` produces a new version of the `Profilename.profile-meta.xml` file which uses 2 spaces for indentation, unlike the 4 spaces for indentation generated by standard sfdx `source:pull` and `source:retrieve` operations.  The result is that git marks every line of the file as a diff, and there is no way to determine what actually changed.

**To Reproduce**

Given a DX project containing a profile:
1. `sfdx force:source:pull`
2. `git add . && git commit -m 'first commit'`
3.  make a change to the profile in scratch org
4. `sfdx sfpowerkit:source:profile:retrieve -m "profilename"`
5. `git diff`

**Expected behavior**
Only the change made in the scratch org appears in the diff

**Screenshots**
![Screen Shot 2020-06-10 at 12 39 08 PM](https://user-images.githubusercontent.com/2294694/84294696-8a3be500-ab17-11ea-99fb-ab0a4d7296da.png)
![Screen Shot 2020-06-10 at 12 39 42 PM](https://user-images.githubusercontent.com/2294694/84294705-8d36d580-ab17-11ea-92ed-bc38b2755964.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.14.5
- Node Version: v12.0.0
- Version of sfpowerkit: 1.45.2
- Salesforce Org Version:  Summer '20 Patch 8 (CS97)

**Additional context**
N/A

**Comment by azlam-abdulsalam** [comment]
Would additional parameters to git diff command help? Such as ignore spaces.

**Comment by jclark-dot-org** [comment]
@azlam-abdulsalam Not especially.  When working on a team, and using multiple git-related tools, relying on a command line switch (or even a config option) isn't going to go well.  And as soon as you need to commit a change, you'll be picking up the changed indentation which will cause issues tracking down the source commit of real changes in the future (e.g., `git blame`).

Because these files are all machine-generated by SF, we can rely on them always having consistent whitespace; this tool should match the whitespace generated by Salesforce.  Likewise, `standalone="yes"` should be removed from the `<?xml?>` processing instruction.

**Comment by azlam-abdulsalam** [comment]
Yeah, agree, will look into it!

**Comment by azlam-abdulsalam** [comment]
@genoud  Can you  have a look into this?

**Comment by genoud** [comment]
Hey @azlamsalam . Yes sure, will have a look.

**Comment by manisfdcsfdx** [comment]
Hey @jclark-dot-org fix is available in beta ``sfdx plugins:install sfpowerkit@beta`` can you test and let us know.
