### ISSUE TITLE
Allow using wildcards to deploy metadata

### ISSUE THREAD

**Issue by RobinWeymans** [Accenture/sfpowerkit#288]
Would it be possible to implement an instruction that allows deploying metadata files matching wildcards?
Something like ```sfdx force:source:deploy -m Layout:Case-*``` to deploy all Case layouts.

The only option right now is to either deploy every layout, or a specific one.

**Comment by crazynammer** [comment]
Have you tried to make a manifest file and put those selected Case layouts in the manifest file? That is a workaround option now like `sfdx force:source:deploy -u OrgAlias -x mainfest/packageCases.xml`

**Comment by azlam-abdulsalam** [comment]
Closing this due to no further activity
