### ISSUE TITLE
Enhancements to sfpowerkit:package:dependencies:install

### ISSUE THREAD

**Issue by manisfdcsfdx** [Accenture/sfpowerkit#293]
**Is your feature request related to a problem? Please describe.**
1. Support installing dependent packages that are created with dependency check. when dependency buildnumber is mentioned as .LATEST. 

2. Enhancements to installationkeys to support mono repo multiple package structure. This format 1:MyPackage1Key 2: 3:MyPackage3Key... is ambiguous on mono repo scenarios.  This enhancement will support **packagename:key** format ``core:key nCino:key vlocity:key``.

3. Support **individualpackage**  to accept package name or package version id.

**Comment by azlam-abdulsalam** [comment]
Closing this as there is an open issue to track it
