### ISSUE TITLE
Checklist execute command

### ISSUE THREAD

**Issue by aly76** [Accenture/sfpowerkit#296]
**Is your feature request related to a problem? Please describe.**
Salesforce deployments always features manual steps and it is as critical as the code/metadata that is being deployed through pipelines.  One approach is to use a YAML file with the manual steps defined which could then be saved as a versionable checklist 

Having defined a yaml schema for manual steps required before a release, we need a `sfpowerkit: checklist:execute` command that guides a release manager through the manual steps /checklist in a terminal, and then outputs a log of which manual steps were completed.  

**Describe the solution you'd like**
The `checklist execute` command should accept the following parameters:

- checklist filepath 
- Alias/username
- Output path for logs

The `execute` command should validate whether the yaml file complies with the schema we have defined by converting it to JSON format and performing a type check against an interface definition. 

Using an interactive command-line interface (e.g. inquirer), the `execute` command iterates through the tasks in a checklist, displaying each task and prompting the user whether the task has been **a)** completed or **b)** skipped. A timer logs the amount of time taken for each task and includes this in the output log.  

The command outputs a checklist log file that lists the outcome for each task, as well as information like the date and user.
**Describe alternatives you've considered**

- Including add, update and delete commands for the checklist
  - Decided that it would be more natural for users to make changes to the runbook through an editor - possibly creating a VScode extension in the future that validates whether the runbook yaml file is compliant with the schema we have defined.

**Additional context**
The log output of the `execute` command can be used to create a dashboard such as in  Azure Pipelines or any other CI/CD, showing the manual steps that were done for a release.

**Comment by azlam-abdulsalam** [comment]
@aly76  Please move this issue to sfpowerscripts, after some consideration sfpowerscripts is ideal for orchestration related tasks
