### ISSUE TITLE
sfdx sfpowerkit:project:diff -r head~1 -d output -x --loglevel trace . creates improper destructive changes.xml

### ISSUE THREAD

**Issue by RajaPaul** [Accenture/sfpowerkit#339]
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <name>ApexClass</name>
    <members>SampleClass1</members>
    <members>force-app/main/default/classes/SampleClass2</members>
.......
```
When I run the command: sfdx sfpowerkit:project:diff -r head~1 -d output -x --loglevel trace
it creates a destructive changes.xml but some lines in the xml file contain the relative class path like **<members>force-app/main/default/classes/SampleClass2</members>**

This should not happen.

**Comment by azlam-abdulsalam** [comment]
Thanks for raising the issue, we wiil upate you shortly on the progress

**Comment by manisfdcsfdx** [comment]
@RajaPaul fix is available in beta, you can verify using beta version sfdx plugins:install sfpowerkit@beta.

fix will be available in regular release [2.x](https://github.com/Accenture/sfpowerkit/milestone/19?closed=1)
