### ISSUE TITLE
Cannot find module '../../../../src/ui/progressBar' - Same as #282

### ISSUE THREAD

**Issue by danmclindon** [Accenture/sfpowerkit#348]
**Describe the bug**
Error when trying to run sfpowerkit:org:profile:diff 

**To Reproduce**

1. sfdx sfpowerkit:org:profile:diff -p "System Administrator"

**Desktop (please complete the following information):**

- OS: WIN10
- Version of sfpowerkit:  2.0.17
- Salesforce Org Version:  Summer 20

**Additional context**
All other commands seem to be fine.

**Comment by manisfdcsfdx** [comment]
@danmclindon hotfix is applied, you may test the fix.
