### ISSUE TITLE
No default record type specified in reconciled profile

### ISSUE THREAD

**Issue by aly76** [Accenture/sfpowerkit#362]
**Describe the bug**
No default record type in profile, after reconciling the profile against the target deployment org. 

**To Reproduce**
Reconcile profile containing a default record type visibility that is removed as part of the reconcile. Then try and deploy the reconciled profile to the target org, which should then cause an error complaining that there is no default record type visibility.

1. sfdx sfpowerkit:source:profile:reconcile
2. sfdx force:source:deploy

**Expected behavior**
Default record type is defined in the profile after reconciliation 

**Screenshots**
<img width="1183" alt="Screen Shot 2020-08-20 at 5 48 12 pm" src="https://user-images.githubusercontent.com/36793262/90731757-74b01c00-e30d-11ea-8356-9c1c785d1f5d.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Node Version 12.16.0
- Version of sfpowerkit 2.0.18
- Salesforce Org Version [ In case of pre release window ]

**Additional context**

**Comment by manisfdcsfdx** [comment]
This is not a bug... Lets say you retrieve a profile from sandbox 1 where Account has got 5 recordtypes and 1st one is set as in default. 

Now you reconcile it against sandbox 2 where only 4th and 5th recordtype exist so 1/2/3 will be wiped out in the profile.

Then try to deploy to sandbox you will get this error, now its devs responsibility to set a default one. we cant automatically set it.

cc: @azlam-abdulsalam
