### ISSUE TITLE
Sandbox refresh command

### ISSUE THREAD

**Issue by ayadav4** [Accenture/sfpowerkit#366]
sfdx sfpowerkit:org:sandbox:refresh - How can start sandbox refresh using this command ? I tried  as below

sfdx sfpowerkit:org:sandbox:refresh -n $(env.name)  -v HubOrg

but got error like  ERROR running sfpowerkit:org:sandbox:refresh:  400 - [{"message":"License Type: bad value for restricted picklist field: undefined","errorCode":"INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST","fields":["LicenseType"]}]

**Comment by azlam-abdulsalam** [comment]
The command usage looks quite right. Do you have the right permissions? What type of Sandbox where you refreshing?

**Comment by manisfdcsfdx** [comment]
@ayadav4 you need to provide either licence type if you want to refresh from prod or clonefrom from sandbox you need refresh copy.
