### ISSUE TITLE
Salesforce sfdx powerkit delta changes commit conflicts

### ISSUE THREAD

**Issue by dineshpsalm** [Accenture/sfpowerkit#376]
Hi team,
My first commit
![git1](https://user-images.githubusercontent.com/59183645/91720712-7ee4dc80-eb8f-11ea-8ea2-e0f0faf1c2b3.png)

My second commit
![git 2](https://user-images.githubusercontent.com/59183645/91720801-a0de5f00-eb8f-11ea-9222-6427801b7a3a.png)

Sfdx power kit diff command output.
![git 3](https://user-images.githubusercontent.com/59183645/91720824-a9369a00-eb8f-11ea-84ab-a7b291cedc5e.png)

Question:
I hope this powerkit compare the changes on one previous commit with recent commit and helps us to push recent delta changes into the org. if that is the case,
then 
1. why should it listing out pmdtest.cls-meta.xml, and Territory_Zip_Code__c-Territory Zip Code Layout.layout-meta.xml in my diff.json file ? Pls see my attached images above. 
2. CreateContactController.xml file is not modified by me on second time ,then how come it added in my diff.json file ?
3. My newly added demofile.xml also not listed in sfdx power kit diff? why
4. how to check my powerkit version number in CLI ? - Pls note i installed recent stable version using "sfdx plugins:install sfpowerkit"

Can anyone help me or direct me to right page to resolve my doubts/queries

**Comment by manisfdcsfdx** [comment]
@dineshpsalm you can run this to see the version

`sfdx plugins --core`

**Comment by manisfdcsfdx** [comment]
@dineshpsalm Also can you run git diff HEAD HEAD~1 to see the output as well

**Comment by dineshpsalm** [comment]
@manisfdcsfdx  -- $ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.4.1 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 49.4.0 (core)
└─ custom-metadata 1.0.7 (core)
sfdx-cli 7.68.6 (core)
sfpowerkit 2.0.19


this is the output. 

I'm getting added, modified files in the output directory I'm pointing but in the same way I like to generate package.xml and metadata folder for the deleted files in the source code. 

Same like what these guys mentioned as "destructivechanges" in this webpage - https://www.npmjs.com/package/sfdx-git-delta

**Comment by manisfdcsfdx** [comment]
@dineshpsalm if you are after destructivechanges we do provide that, you need to use -x | --generatedestructive  falg. Since we are generating incremental delta changes in source format there is no need to package.xml. you still need package.xml you may need to run source:convert on that delta output project

```
USAGE
  $ sfdx sfpowerkit:project:diff -d <string> [-r <string>] [-t <string>] [-x] [-b <array>] [-p <array>] [--apiversion <string>] [--json]
  [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]

OPTIONS
  -b, --bypass=bypass                                                               list of path to ignore, if diff found on the repo
  -d, --output=output                                                               (required)  The output dir where the incremental project will be created

  -p, --packagedirectories=packagedirectories                                       project paths to run diff, if this is passed then override the path in sfdx-project.json

  -r, --revisionfrom=revisionfrom                                                   Base revision from where diff is to be generated, required if diff file is ommited

  -t, --revisionto=revisionto                                                       [default:HEAD] Target revision to generate the diff

  -x, --generatedestructive                                                         If set to true, the command will also generate a destructiveChangePost.xml file in the
                                                                                    output folder.

  --apiversion=apiversion                                                           override the api version used for api requests made by this command

  --json                                                                            format output as json

  --loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL)  [default: info] logging level for this command invocation

EXAMPLE
  $  sfdx sfpowerkit:project:diff --revisionfrom revisionfrom --revisionto revisionto --output OutputFolder
```

**Comment by dineshpsalm** [comment]
thats great @manisfdcsfdx  i like to know two more things 
1. When I mention "/powerdir" in my command it automatically stores my output in path "C:\Users\a668318\AppData\Local\Programs\Git\powerdir". In this case, how  do I define my own path ? 

2. If output dir is not changeable, then what would be the default path in linux environment similar to above one ?

**Comment by dineshpsalm** [comment]
I usually use source:retrieve command to retrieve from test and use "sfdx force:source:deploy --manifest c:\...\manifest\package.xml -u prod" to deploy my components into prod org. When I'm using power kit, it is generating files in output folder where I defined in command. Now point here is, How do I deploy this into my destination org. I'm asking this because, usually I use package.xml to deploy but here in the output folder I can see only diff.json file. Do we have way to deploy using diff.json in to destination org ? or I need to convert this into package.xml to deploy my changes generated by powerkit. Pls confirm

**Comment by manisfdcsfdx** [comment]
@dineshpsalm you could pass the sourcepath with delta dir to deploy

`sfdx force:source:deploy --sourcepath /powerdir/force-app -u prod`

**Comment by dineshpsalm** [comment]
@manisfdcsfdx  - thanks for input mani. I have two more questions here. 
1. Is there any way to convert delta source into package.xml ? 
2. what is the use of diff.json file which generated using sfdx powerkit ? just for view purpose or we can use it for deployment ? if yes, how to use json file for deployment ?

**Comment by manisfdcsfdx** [comment]
@dineshpsalm -

> 1. Is there any way to convert delta source into package.xml ?

As we generate the output in source format actually there is no need for package.xml, if you still need package.xml you may need to run [source:convert](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_convert) to get your own package.xml from the delta output.

> 2. what is the use of diff.json file which generated using sfdx powerkit ? just for view purpose or we can use it for deployment ? if yes, how to use json file for deployment ?

diff.json is not for your deployment. it is used for reporting purpose only, incase if you want to generate a report in your CI. to be more clear all sfdx commands returns json output when you run the commands with --json flag.

**Comment by dineshpsalm** [comment]
you are really helpful @manisfdcsfdx . Appreciate it keep it up
