### ISSUE TITLE
Updating Azure DevOps variable group variable from Azure Pipeline

### ISSUE THREAD

**Issue by ayadav4** [Accenture/sfpowerkit#379]
Hi Team,

Please help me to update Azure Devops Variable groups variable  from Azure  release pipeline.
It would be great help

Regards,
Anil Yadav

**Comment by azlam-abdulsalam** [comment]
@ayadav4  Please raise this issue in sfpowerscripts https://github.com/accenture/sfpowerscripts as this is only sfpowerkit related
