### ISSUE TITLE
Error in project:orgdiff

### ISSUE THREAD

**Issue by dykim-daniel** [Accenture/sfpowerkit#381]
**Describe the bug**
The error comes up when I run project:orgdiff command.

Error Message
- TypeError: Cannot read property 'bold' of undefined

**To Reproduce**

sfdx sfpowerkit:project:orgdiff --folder directory  -u <env_alias>

**Expected behavior**
N/A

**Screenshots**
<img width="572" alt="Screen Shot 2020-09-04 at 11 53 29 am" src="https://user-images.githubusercontent.com/63702787/92190823-71886480-eea5-11ea-8efb-c0c5143a2948.png">

<img width="1366" alt="Screen Shot 2020-09-07 at 12 21 28 pm" src="https://user-images.githubusercontent.com/63702787/92342815-59af1b80-f105-11ea-9251-0a531af869c0.png">

**Desktop (please complete the following information):**
- OS: Mac
- Node version: N/A
- Version of sfpowerkit: 2.1.5
- Salesforce Org Version: N/A

**Additional context**
N/A

**Comment by manisfdcsfdx** [comment]
--folder is not a valid flag. readme and example needs to updated. please use `-f or --filesorfolders` with valid path.
