### ISSUE TITLE
sfpowerkit command fails to run, if it run outside the sfdx project directory

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#390]
**Describe the bug**
Many of the sfpowerkit namespaces (org, packages) doesn't have the requirement of running inside a sfdx project directory. It could be run from anywhere. A recent update in @salesforce/core has broken the functionality, which resulted in all the commands to be triggered only from a sfdx project directory.

**To Reproduce**
Run any commands that do not have the sfdx project director requirement. For eg:

1. sfdx sfpowerkit: package:version:info -u <org_name>

**Expected behavior**
The command should be able to be triggered from any directory

**Screenshots**
![image](https://user-images.githubusercontent.com/43767972/93166178-46cdc400-f761-11ea-8536-ffe02ae2c423.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: 12.16.3
- Version of sfpowerkit[e.g 1.45.0]: alpha (from source)
- Salesforce Org Version [ In case of pre release window ]

**Additional context**
The issue is already reported in https://github.com/forcedotcom/cli/issues/615

**Comment by manisfdcsfdx** [comment]
Closing the issue as the fix is applied for forcedotcom/cli#615
