### ISSUE TITLE
sfpowerkit:source:profile:reconcile - Not reconciling flow

### ISSUE THREAD

**Issue by ayadav4** [Accenture/sfpowerkit#394]
Hi Team, 

I am trying to reconcile profiles retrieved from Production  against the metadata we got in our project.  I just observed that it is not removing flow related metdata from  profile xml files. It should remove them as well as I do not have any flow in my project.

**Comment by azlam-abdulsalam** [comment]
@ayadav4 Can you provide the parameters used and details like API version of the org etc

**Comment by ayadav4** [comment]
Hi Azlam,

I ran below command from VS code terminal with production as default org

sfdx sfpowerkit:source:profile:retrieve

After running the above command, I got all the profiles in my project  src/main/default/profiles folder.

then I ran below command to reconcile profiles against the my project metadata.

sfdx sfpowerkit:source:profile:reconcile  --folder src, corenew  -s

As per my understanding, after running the above, there should not be any flow related metadata in my project both in src, corenew.

But see entries like below in profiles.


<flowAccesses>
    <enabled>false</enabled>
    <flow>xyz1</flow>
  </flowAccesses>
  <flowAccesses>
    <enabled>false</enabled>
    <flow>xyz2</flow>
  </flowAccesses>
  <flowAccesses>
    <enabled>false</enabled>
    <flow>xyz3</flow>
  </flowAccesses>
  <flowAccesses>
    <enabled>false</enabled>
    <flow>xyz4</flow>
  </flowAccesses>

**Comment by manisfdcsfdx** [comment]
Thanks @ayadav4 we will look into the issue.

**Comment by manisfdcsfdx** [comment]
@ayadav4 can you run the command with --loglevel bebug and check Flow Access reduced from count. I just ran it on my source with sourceonly flag it seem to work fine. 

Below was on a project having 156 Flow so the reconciled profile resulted with 156 flowaccess
![image](https://user-images.githubusercontent.com/44075423/93983496-fa6c2f00-fdc5-11ea-9f0b-4b754739352e.png)

Below was on a project having No Flow so the reconciled profile resulted with No flowaccess
![image](https://user-images.githubusercontent.com/44075423/93984034-a877d900-fdc6-11ea-8626-c9d2e593ac3a.png)

**Comment by ayadav4** [comment]
I installed this plugin 8-9 month before  in my local machine, is this because of that I am facing issue?

**Comment by ayadav4** [comment]
@manisfdcsfdx - I ran above command, please see below scree shot.

![image](https://user-images.githubusercontent.com/35283334/94102651-419f0200-fe50-11ea-8e0e-e243312f9521.png)

**Comment by ayadav4** [comment]
@manisfdcsfdx -I ran above command . Please see below screen shot.

![image](https://user-images.githubusercontent.com/35283334/94102781-8f1b6f00-fe50-11ea-87f8-7e45ee56440c.png)

**Comment by manisfdcsfdx** [comment]
@ayadav4 well it looks like using version 1.26.1 which is 1 year old. sfpowerkit current version is 2.1.6 https://www.npmjs.com/package/sfpowerkit. can you please update the plugin using `sfdx plugins:update` or install latest version `sfdx plugins:install sfpowerkit@latest`

**Comment by ayadav4** [comment]
@manisfdcsfdx - After installing latest version, it is working properly. Thanks for all your help.

**Comment by manisfdcsfdx** [comment]
@ayadav4 Glad your issue is resolved.
