### ISSUE TITLE
sfdx sfpowerkit:project:diff - Not Capturing All Deltas from Commit Showing in Repo

### ISSUE THREAD

**Issue by vuha-acn** [Accenture/sfpowerkit#397]
**Describe the bug**
When executing the sfdx sfpowerkit:project:diff command and comparing the output directly to my repo between the 2 commits, there are missing metadata such as customMetadata, layouts, objects, and labels that was expected to be included to have a 1:1 match.

**To Reproduce**

1. sfdx sfpowerkit:project:diff --revisionfrom abc --revisionto 123 --output delta

**Expected behavior**
Output directory matches 1:1 with what I see in the repot diff report for the commit.

**Screenshots**
Differs per commit.  

**Desktop (please complete the following information):**

- OS: MacOS
- Node Version - v14.4.0
- Version of sfpowerkit[e.g 1.45.0] - Latest
- Salesforce Org Version [ In case of pre release window ] - Summer '20 / Winter '21

**Additional context**
Experimenting with command as one-off deployment options for deployments.  Expected also a manifest file to be created instead as well to pull the records down as well if needed.  This could be a enhancement or feature flag to enable manifest to be created only besides the folder structure.  Also, when running the command, it did not warn the user if it's a current folder that has data in it.  This override all my files and I couldn't restore it as it wasn't a folder that was being tracked to by git.  A check to see if any contents are in there first would be good to avoid data loss.

**Comment by azlam-abdulsalam** [comment]
Closing this as its not reproducible
