### ISSUE TITLE
Sfpowerkit Instllation error

### ISSUE THREAD

**Issue by ayadav4** [Accenture/sfpowerkit#407]
Hi Team,

I trying to install sfpoerkit into my machine( windows). It is faling with below error. Could you please suggest some workaround if possible.

sfdx plugins:install sfpowerkit
    Error: unable to get local issuer certificate
    Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

**Comment by manisfdcsfdx** [comment]
@ayadav4 can you provide screenshot

**Comment by ayadav4** [comment]
@manisfdcsfdx - as requested, please find below screenshot. Please note that this is company laptop.

![image](https://user-images.githubusercontent.com/35283334/95430627-a6d31700-0969-11eb-8c20-bd2a09ecd702.png)

**Comment by manisfdcsfdx** [comment]
@ayadav4 can you try it in any other machine please. Looks like this is SSL certificate issue in your machine you may need to work with your company IT team.

**Comment by ayadav4** [comment]
@manisfdcsfdx it got installed, thanks for help

**Comment by manisfdcsfdx** [comment]
@ayadav4  Glad your issue is resolved
