### ISSUE TITLE
The flag "resultasstring" doesn't seem to work.

### ISSUE THREAD

**Issue by dweaver33** [Accenture/sfpowerkit#417]
I would expect this to produce a list of all the test classes as comma separated, however, when running the command, I get the same table output:

`sfdx sfpowerkit:source:apextest:list -p force-app --resultasstring`

https://github.com/Accenture/sfpowerkit/blob/44f67a1224c73971210d82c360c93d22982160ea/src/commands/sfpowerkit/source/apextest/list.ts#L92

**Comment by manisfdcsfdx** [comment]
@dweaver33  we returning array or comma separated string to json output when you run the command with `--json`. happy to print the string in console in case of `--resultasstring` flag

**Comment by dweaver33** [comment]
@manisfdcsfdx, maybe we could give the option somehow?

**Comment by manisfdcsfdx** [comment]
@dweaver33 ya added a enhancement to print comma separated string oppose to table in case of `--resultasstring`

**Comment by manisfdcsfdx** [comment]
@dweaver33 you can check the fix in beta version. nov 2nd fix will be available in regular version.

**Comment by dweaver33** [comment]
@manisfdcsfdx, works great!  Thank you!
