### ISSUE TITLE
"sfpowerkit:project:diff" command fails to generate the delta between 2 commits

### ISSUE THREAD

**Issue by maazinbeig** [Accenture/sfpowerkit#421]
**Description:**
Using the "sfpowerkit:project:diff" command, the delta fails to generate the files between commits.

**To Reproduce:**
Do a project diff using command below and the latest version of sfpowerkit:
- **Command used:** sfdx sfpowerkit:project:diff --revisionfrom $commitA --revisionto $commitB --output "outputfolder"
- **Error:** Cannot read property 'directoryName' of undefined

**Desktop**
- OS: Windows
- Node Version: Latest
- Version of sfpowerkit: Latest (2.3.4)

**Work around:**
Using previous version of sfpowerkit (2.2.8) successfully generated the delta.

**Comment by azlam-abdulsalam** [comment]
@maazinbeig  thanks for raising it. Fixed it in v2.3.6
