### ISSUE TITLE
org:manifest:build --quickfilter appears to function opposite of the description

### ISSUE THREAD

**Issue by aheber** [Accenture/sfpowerkit#424]
**Describe the bug**
Adding a `--quickfilter` flag to the `org:manifest:build` command causes _only_ the "filtered" type to be generated, rather than excluding that type. 
The flag text says this should be inverted, and should be an "exclude" list.
`comma separated values  of metadata type, member or file names to be excluded while building the manifest`

**To Reproduce**
`sfdx sfpowerkit:org:manifest:build --quickfilter ApexClass` should be outputting a full manifest _excluding_ ApexClass type. It is actually only outputting the ApexClass type and excluding all others.

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version: node-v12.18.3 (installed via SFDX)
- Version of sfpowerkit[e.g 1.45.0]: sfpowerkit 2.3.6
- Salesforce Org Version: Winter '21

**Additional context**

**Comment by manisfdcsfdx** [comment]
@aheber Thanks for the raising PR.
