### ISSUE TITLE
Enhance sfpowerkit:org:scratchorg:delete to allow specific scratchorg to be deleted

### ISSUE THREAD

**Issue by seanong-athena** [Accenture/sfpowerkit#441]
**Is your feature request related to a problem? Please describe.**
- Currently, we are using docker images with bitbucket pipelines.
- Docker images creates a "fresh" instance and hence no sfdx information is stored.
- We are able to use `sfpowerkit:auth:login` to login to the DevHub.
- However, since we are using the user/pass flow, we are unable to delete scratch orgs using `sfdx force:org:delete`.
- There is currently a `sfpowerkit:org:scratchorg:delete` command, but this command deletes all scratchorgs owned by the user.

**Describe the solution you'd like**
- Enhance `sfpowerkit:org:scratchorg:delete` to provide a `--username` parameter, e.g. `test-pvcdapwmy5mj@example.com`

**Describe alternatives you've considered**
- The alternative is to use the the JWT bearer token flow instead of user/pass.
- However, we prefer user/pass since we have a feature that automatically rotates the password daily.

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx whats your take on it? Seems possible

**Comment by manisfdcsfdx** [comment]
Yea @azlam-abdulsalam it is possible we can accept `--username`  to delete a specific scratch orgs. 

@seanong-athena
