### ISSUE TITLE
while creating delta pkg .forceignore not getting copied to working directory

### ISSUE THREAD

**Issue by ramesh-karanji** [Accenture/sfpowerkit#445]
Create Delta Package based on two commits task is failing with below error while delta package creation
##[error]ENOENT: no such file or directory, open 'portal_src_delta/.forceignore'

**Comment by manisfdcsfdx** [comment]
@azlam-abdulsalam not able to reproduce this one, we are handling project not having forceignore. i have tested in project where forceignore not exist as well. 

keeping this open to see if @ramesh-karanji facing this anymore.

**Comment by azlam-abdulsalam** [comment]
Closing this as no further feedback from @ramesh-karanji . Please feel free to reopen of required
