### ISSUE TITLE
Login Flows component in profiles

### ISSUE THREAD

**Issue by maazinbeig** [Accenture/sfpowerkit#460]
**Describe the bug**
"LoginFlow" metadata component in .profile file not detected using "sfdx sfpowerkit:project:diff"

**To Reproduce**
1. Make changes/ add "Login Flow" on a sandbox (Metadata for login flow introduced by Salesforce in API 51)
2. More information on adding loginFlow metadata can be found here: https://developer.salesforce.com/docs/atlas.en-us.230.0.api_meta.meta/api_meta/meta_profile.htm 
3. sfdx sfpowerkit:project:diff command creates an empty package i.e loginFlow is not detected.

**Expected behavior**
"Login Flow" should be retrieved in the profiles.

**Screenshots**
Example of profile file with login flow should look like below:
![image](https://user-images.githubusercontent.com/60119360/104880471-b673ea00-59b3-11eb-82bf-a06b501962c3.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version latest
- Version of sfpowerkit: latest
- Salesforce Org Version: Spring 21
- API version: 51

**Additional context**
As designed, if you are using API 51 and Spring 21' and the profile file does not contain the "Login Flow" component. If the target org has login flow associated to that profile, it will get deleted upon deployment.

Workaround: Change the repo API to 48. But this may not be feasible if components released as a part of API version > 48 are checked in.

**Comment by azlam-abdulsalam** [comment]
@genoud  Can you have a look?

**Comment by azlam-abdulsalam** [comment]
@genoud  this affects profile commands as well

**Comment by maazinbeig** [comment]
The issue that caused the login flows to get deleted from the target org upon deployment of any permission in profiles (field permission/ apex class permission / page permission) has been fixed. Below article has all details:

field permission/ apex class permission / page permission
