### ISSUE TITLE
The pool option --batchsize do nothing

### ISSUE THREAD

**Issue by nabondance** [Accenture/sfpowerkit#461]
**Describe the bug**
The command `sfpowerkit:pool:create --configfilepath=config/so-pool-config.json --targetdevhubusername=DevHub --batchsize=2` doesn't take in consideration the --batchsize option.
No matter the number of the batchsize (1,2,6,10), it always create every scratch org, like if the option doesn't exist.

**To Reproduce**

1. Having a config file at config/so-pool-config.json with more than 1 org to be created
2. sfpowerkit:pool:create --configfilepath=config/so-pool-config.json --targetdevhubusername=DevHub --batchsize=2
3. Every scratch orgs of the config file are created

**Expected behavior**
Create only the number of scratch org requested in the batchsize option.

**Screenshots**
config json :
![image](https://user-images.githubusercontent.com/32196400/105048760-3067aa00-5a6c-11eb-80a9-77040efc2c09.png)

command results :
![image](https://user-images.githubusercontent.com/32196400/105048837-4d9c7880-5a6c-11eb-9b4b-376aaef03967.png)
![image](https://user-images.githubusercontent.com/32196400/105048868-5725e080-5a6c-11eb-8571-86b56547117d.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node.js v12.18.3
- sfpowerkit 2.5.7
- Salesforce Org Version: Winter '21 Patch 17.3

**Additional context**
It's not a recent bug, I was never able to make this option work.

**Comment by azlam-abdulsalam** [comment]
@nabondance Batch size is to control the number of parallel threads used for running the scripts (usually for installing packages). 

When you are running in user mode, like in the example provided, the number of scratch orgs allocated  is a sum of max_allocation for all users
