### ISSUE TITLE
PMD Document Version Does Not Match Error

### ISSUE THREAD

**Issue by qswh** [Accenture/sfpowerkit#462]
**Describe the bug**
Running this command in my local throw error 
sfdx sfpowerkit:source:pmd -d force-app -r sfpowerkit -f text
error as below.
net.sourceforge.pmd.RuleSetNotFoundException: Can't find resource 'null' for rule 'sfpowerkit'.  Make sure the resource is a valid file or URL and is on the CLASSPATH

This seems causing issue in SFpowerscript as well with same ruleset and error message is
##[error]%25error="1660003";%25:The document version does not match

**To Reproduce**

1. sfdx sfpowerkit:source:pmd -d force-app -r sfpowerkit -f text

**Expected behavior**
No error should occur
**Screenshots**
NA

**Desktop (please complete the following information):**

- OS: Mac OSX M1
- Node Version - 15.3
- Version of sfpowerkit[e.g 1.45.0] - should be latest as sfpowerscript reports error from pipeline
- Salesforce Org Version - Spring 21 preview

**Additional context**
NA

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  Need to update the default PMD version as well as update the rules
