### ISSUE TITLE
Custom labels not being created in delta package

### ISSUE THREAD

**Issue by SeanCarroll1** [Accenture/sfpowerkit#471]
**Describe the bug**
When running the **sfpowerkit:project:diff** command, the delta that is created is missing custom labels. All of the other metadata appears to be correct, apex class, lwc, layouts etc were all created. An empty labels folder is created in the delta package.
I have a pull request open where I can see the changes for custom labels, if I switch branches and do a manual diff on the custom labels file I can see the custom label changes are correct on the branches.

**To Reproduce**

1. sfdx sfpowerkit:project:diff --revisionfrom branch1--revisionto branch2 --output deltaPackage

**Expected behavior**
Custom label file created with the new custom label values

**Screenshots**
![image](https://user-images.githubusercontent.com/5614304/106957030-7a57bd80-6705-11eb-809f-a872f12d514d.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version - v12.18.3
- Version of sfpowerkit - latest (Have also tried beta)
- Salesforce Org Version Spring '21 Patch 7.1

**Additional context**
Custom labels seem to be the only metadata not being created. Everything else in the pull request is in the delta package.

**Comment by manisfdcsfdx** [comment]
@SeanCarroll1 can you check the diff.json in deltaPackage folder see if you can find the labels there. 

It is working for me.
![image](https://user-images.githubusercontent.com/44075423/107164799-a2e0ff80-6a04-11eb-821b-56792f407445.png)

**Comment by SeanCarroll1** [comment]
Hi @manisfdcsfdx 

I created a new branch with one new custom label and tried creating a delta between the two.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/5614304/107430921-c9319880-6af3-11eb-8b95-e40ec5a30097.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/5614304/107430930-cb93f280-6af3-11eb-9c42-a24bfd1220b8.png)

The diff.json is empty, it does have the labels folder so it seems it does recognize it is where the difference is.

In your screenshot, the delta package looks like it's in metadata format? rather than source format. 

In the documentation for the project diff command, it says **"This command works with a source format based repository only. Utilize the command during a transition phase where an org is transformed to a modular architecture composing of multiple projects."**

**Comment by manisfdcsfdx** [comment]
Hey @SeanCarroll1, No Actually my project is in source format only.  looks like you are the one using metadata format. in your screenshot i can see **custombales.labels** which is metadata format extension. source format will have extension as **CustomLabels.labels-meta.xml**

**Comment by SeanCarroll1** [comment]
Hey @manisfdcsfdx 

The -meta.xml portion is hidden, I am using intellij & illuminated cloud (It also hides the meta file for LWC). I attached images of the branch's metadata in VS code. Below is the same branch.

![image](https://user-images.githubusercontent.com/5614304/107524293-9c2cc680-6b83-11eb-911f-06cb05139626.png)

I ran the command **sfpowerkit:project:diff** again with logs
![image](https://user-images.githubusercontent.com/5614304/107525510-e8c4d180-6b84-11eb-84c2-1c30ad77f479.png)

Same result with an empty label folder and diff.json
![image](https://user-images.githubusercontent.com/5614304/107525572-f712ed80-6b84-11eb-9644-90af42fd8117.png)

It doesn't appear to copy it over for custom labels. I added a comment to one of the apex classes and committed it to the same branch that has a label change.  I can see the command copying the apex class over and it does appear in the delta package.
 
![image](https://user-images.githubusercontent.com/5614304/107526472-e0b96180-6b85-11eb-9b3b-2c626c142c67.png)

Is there something I am missing specifically for custom labels? Thanks.

**Comment by manisfdcsfdx** [comment]
@SeanCarroll1  may i know what is your api version in your sfdx-project.json. I will try it out again in fresh repo and get back to you.

**Comment by SeanCarroll1** [comment]
Hi @manisfdcsfdx, of course 

`{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "50.0"
}`

Let me know if anything else, thanks

**Comment by manisfdcsfdx** [comment]
@SeanCarroll1 I forked[ lwc-recipes](https://github.com/manisfdcsfdx/lwc-recipes) repo did some digging looks everything working fine. 

Created a [PR 1](https://github.com/manisfdcsfdx/lwc-recipes/pull/1) to added a new custom label file and committed the delta result as well.

Created a [PR 1](https://github.com/manisfdcsfdx/lwc-recipes/pull/2) to add and remove custom label in existing file and committed the delta result as well.

can you check this.

**Comment by SeanCarroll1** [comment]
Hi @manisfdcsfdx,

I cloned your repo and ran the same command and received an error - parsing diff
![image](https://user-images.githubusercontent.com/5614304/107817037-8d8d0d80-6d43-11eb-9c8f-08eec8f6d7bc.png)


I tried reinstalling the plugin, sfdx and vs code but still receiving this error. I've not made any changes to the branch.

**Comment by manisfdcsfdx** [comment]
@SeanCarroll1 - Interesting i will do some more digging again in different OS also, will get back. @azlam-abdulsalam any thoughts ?

**Comment by azlam-abdulsalam** [comment]
@SeanCarroll1  @manisfdcsfdx  let me get back to both of you. Thx!

**Comment by manisfdcsfdx** [comment]
@SeanCarroll1 i tested in different machines and different OS cant find any issue. is it possible for you to test this in any other machine and confirm the behavior over there?

**Comment by SeanCarroll1** [comment]
Hi @manisfdcsfdx , 

I can confirm that it worked on another computer when I cloned your repo and ran the same commands. 

I will try to look into what is causing the issue, the only difference I am aware of isthe  java version is older on the laptop that the commands do not work on.

**Comment by manisfdcsfdx** [comment]
Thanks for the confirmation @SeanCarroll1, I will keep this issue open for now and let us know if you anything that is making this inconsistency. If there is any issue with the command we will try to fix else we can close it.
