### ISSUE TITLE
sfdx sfpowerkit:pool:fetch get "Provisioning in progress" scratch orgs

### ISSUE THREAD

**Issue by nabondance** [Accenture/sfpowerkit#478]
**Describe the bug**
Running the command `sfdx sfpowerkit:pool:fetch --tag=myTag --targetdevhubusername=DevHub` get scratch org still in status `Provisioning in progress`.

**To Reproduce**
1. Create a pool using `sfdx sfpowerkit:pool:create --configfilepath=config.json --targetdevhubusername=DevHub`.
2. The pool is configured to run custom script on creation.
3. Scratch orgs are still in status `Provisioning in progress`.
4. Get a scratch org from the pool using `sfdx sfpowerkit:pool:fetch --tag=myTag --targetdevhubusername=DevHub`
5. The scratch org is still provisioning with the custom script but "Assigned" to an user.

**Expected behavior**
Having scratch org only when they are in status "Available".
Having a message when there is no "Available" scratch orgs.

**Screenshots**
![pool_get_provisionning](https://user-images.githubusercontent.com/32196400/109194111-63067000-7799-11eb-9f0c-381efef4f848.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: node-v12.18.3
- Version of sfpowerkit: sfpowerkit 2.6.5
- Salesforce Org Version : 51

**Additional context**
It worked before, the last time I tried was in release 42.

**Comment by azlam-abdulsalam** [comment]
@nabondance  can you confirm you have updated the DevHub with latest prerequisites. ?

@manisfdcsfdx  fyi

**Comment by nabondance** [comment]
Hi @azlam-abdulsalam,
I've pushed the [latest folder](https://github.com/Accenture/sfpowerkit/tree/main/src_saleforce_packages/scratchorgpool/force-app/main/default) using [the doc](https://github.com/Accenture/sfpowerkit/wiki/Getting-started-with-ScratchOrg-Pooling#1-install-the-supporting-fields-and-validation-rule-to-devhub) in the DevHub if it's your question.
Tell me if you where talking about another prerequisite.

**Comment by azlam-abdulsalam** [comment]
No, then its all fine, is this a repeated behaviour and are you getting incomplete orgs?

**Comment by nabondance** [comment]
Hi,
I've done more testing on this issue:
- Each time I have a scratch org in "Provisioning in progress" I can fetch it and assign it to me.
- It looks like the script doesn't stop executing.

But it's still an issue, if an user/CI get a scratch org and push things while the script isn't finished, it won't work or will break the scratch org.

I've found a workaround if someone else have the same issue :
Modifying/Adding the Validation rule in the DevHub to prevent from changing status when the status is "In Progress".
`ISPICKVAL(PRIORVALUE(Allocation_status__c),'In Progress') &&
ISCHANGED(Allocation_status__c)`

**Comment by azlam-abdulsalam** [comment]
Looking at it,  @manisfdcsfdx  as per the workflow only Scratch Orgs that have allocated status could move to assigned

https://github.com/Accenture/sfpowerkit/blob/main/src_saleforce_packages/scratchorgpool/force-app/main/default/workflows/ScratchOrgInfo.workflow-meta.xml

**Comment by azlam-abdulsalam** [comment]
Fixed in upcoming release tomorrow
