### ISSUE TITLE
sfdx sfpowerkit:pool:create doesn't increment numbers well

### ISSUE THREAD

**Issue by nabondance** [Accenture/sfpowerkit#479]
**Describe the bug**
Running the command `sfdx sfpowerkit:pool:create --configfilepath=config.json --targetdevhubusername=DevHub` creates the required number of scratch orgs but says "Creating Scratch  Org  i_org of MAX.." with incorrect i_org indentation.
The indentation loops on smaller then it should. 
For example, if the number of required scratch org is 11, for each scratch org we have:

> Creating Scratch  Org  1 of 11..
> Creating Scratch  Org  2 of 11..
> Creating Scratch  Org  1 of 11..
> Creating Scratch  Org  2 of 11..
> Creating Scratch  Org  1 of 11..
> Creating Scratch  Org  2 of 11..
> Creating Scratch  Org  1 of 11..
> Creating Scratch  Org  2 of 11..
> etc...

The main issue is that we only have "scratch org number 1" and "scratch org number 2" in the log. It only creates 2 log files: SO1.log and SO2.log. In this example we have 5 scratch orgs script writing in the same file, making it quite impossible to understand and debug.

**To Reproduce**
1. `sfdx sfpowerkit:pool:create --configfilepath=config.json --targetdevhubusername=DevHub`
2. Not having one log file per scratch org creating

**Expected behavior**
Having one log file per scratch org script.

**Screenshots**
![pool_number_11](https://user-images.githubusercontent.com/32196400/109195808-4408dd80-779b-11eb-8245-4d14d18ae765.png)
![pool_log_SO](https://user-images.githubusercontent.com/32196400/109195429-c93fc280-779a-11eb-9b04-a80fcdb72e86.png)

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 9.9
- Node Version: node-v12.18.3
- Version of sfpowerkit: sfpowerkit 2.6.5
- Salesforce Org Version: 51

**Additional context**
Indentation and log number works well for small amount of scratch org creation (1, 2, 3).

**Comment by azlam-abdulsalam** [comment]
I believe this is in user mode? 

I have noticed this and will be fixing it.

**Comment by nabondance** [comment]
Yes I use a poolUsers list in the pool config json.

That's great if it will be fixed soon, thank you.

**Comment by azlam-abdulsalam** [comment]
@nabondance  aplogies for the delay, finally got a chance to address it, will be part of the next release
