### ISSUE TITLE
Cannot reconcile profile with "-s" flag

### ISSUE THREAD

**Issue by hsaraujo** [Accenture/sfpowerkit#487]
**Describe the bug**
Cannot reconcile profile with "-s" flag.
By looking at the code,  apparently a bug was implemented in the latest 2 releases. The reconcile methods on the "profileReconcile.ts" class are now instantiating this "MetadataRetriever" class which requires a Connection as an argument in the constructor.
The problem is that when the "-s" flag passed, you shouldn't need a connection as it is all done within the source folder.

I hope the description helps.

**To Reproduce**

1. sfdx sfpowerkit:source:profile:reconcile -f force-app -s

**Expected behavior**
Cleans all profiles in the force-app folder with the contents that are being tracked in the source repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/1737178/110031335-a9605e00-7d9b-11eb-8c86-77e966fda7c2.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Node Version 15.6
- Version of sfpowerkit: 2.7.7
- Salesforce Org Version Spring 21 (api 51)

**Comment by azlam-abdulsalam** [comment]
@hsaraujo  Thanks for reporting! Will be fixing it in a short while

@manisfdcsfdx  fyi

**Comment by manisfdcsfdx** [comment]
@hsaraujo fix is available in v2.7.8 try `sfdx plugins:install sfpowerkit@2.7.8`
