### ISSUE TITLE
When the package ID is put as 15 character it should auto convert it to 18 character

### ISSUE THREAD

**Issue by qswh** [Accenture/sfpowerkit#489]
**Is your feature request related to a problem? Please describe.**
If package id is used in 15 character format, package: dependencies: install is unable  to detect whether the same package is already installed in the org.
**Describe the solution you'd like**
Auto convert it to 18 character based on this logic. 
https://help.salesforce.com/articleView?id=000319308&type=1&mode=1

**Comment by qswh** [comment]
https://www.gammone.com/programmazione/come-convertire-id-salesforce-da-15-a-18-caratteri this might be better to check its logic.

**Comment by manisfdcsfdx** [comment]
@qswh I have applied the fix in v.2.8.2 can you try it using `sfdx plugins:install sfpowerkit@2.8.2` let us know if works for you.
