### ISSUE TITLE
PMD java exception ApexTreeBuilder

### ISSUE THREAD

**Issue by gudavies** [Accenture/sfpowerkit#509]
**Describe the bug**
Running PMD cmd

**To Reproduce**
Retrieve few apex classes & triggers
sfdx sfpowerkit:source:pmd --version=6.34.0

**Expected behavior**
PMD report to be returned

**Actual Error**
C:\code\project>sfdx sfpowerkit:source:pmd --version=6.34.0
WARNING: apiVersion configuration overridden at "51.0"
INFO [2021-04-27 06:43:21.840 +0000] (sfpowerkit): Found Java Home at C:\Program Files\Zulu\zulu-11
INFO [2021-04-27 06:43:21.846 +0000] (sfpowerkit): Initiating Download of  PMD
INFO [2021-04-27 06:43:29.736 +0000] (sfpowerkit): Downloaded PMD 6.34.0
INFO [2021-04-27 06:43:30.674 +0000] (sfpowerkit): Extracted PMD 6.34.0
INFO [2021-04-27 06:43:30.724 +0000] (sfpowerkit): PMD release 6.34.0
INFO [2021-04-27 06:43:30.725 +0000] (sfpowerkit): Now analyzing force-app
INFO [2021-04-27 06:43:40.878 +0000] (sfpowerkit): PMD Exited with some exceptions
ERROR [2021-04-27 06:43:40.879 +0000] (sfpowerkit):     at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:127)

**Desktop (please complete the following information):**

Windows 10.0.18363
sfpowerkit 2.8.7
sfdx-cli/7.90.2 win32-x64 node-v12.16.1
Node.js v12.16.1.
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-CA (build 11.0.4+11-LTS, mixed mode)

**Additional context**
Tried so far to:
Set apiVersion to v50.0, 51.0
Removed all files from project forceapp folder except classes/triggers.

Known to work on another Vscode client on similar classes, java version used is JDK11 as opposed to Zulu11 as main difference.

**Comment by rody** [comment]
Hello @gudavies,
It seems to be an issue with the Apex parser when building the AST.
Can you try the following:

`sfdx sfpowerkit:source:pmd --version=6.30.0`

This will use the previous PMD version that was used by sfpowerkit. If the error disappears, it might be an issue with PMD itself.
If it does not solve the issue, can you identify the file (or the minimum set of files) to reproduce the error, and share them so I can investigate this issue?

**Comment by gudavies** [comment]
C:\code\project>sfdx sfpowerkit:source:pmd --version=6.30.0
WARNING: apiVersion configuration overridden at "50.0"
INFO [2021-05-03 05:56:00.726 +0000] (sfpowerkit): Found Java Home at C:\Program Files\Zulu\zulu-11
INFO [2021-05-03 05:56:00.776 +0000] (sfpowerkit): PMD release 6.30.0
INFO [2021-05-03 05:56:00.776 +0000] (sfpowerkit): Now analyzing force-app
INFO [2021-05-03 05:56:24.443 +0000] (sfpowerkit): PMD Exited with some exceptions
ERROR [2021-05-03 05:56:24.444 +0000] (sfpowerkit):     at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:89)

**Comment by gudavies** [comment]
Per current analysis, identified has to do with something in one of the classes, as a fresh project with few classes worked.
remove those containing ?.
however something else is still causing same issue
