### ISSUE TITLE
sfpowerkit:project:diff not generating recordType when businessProcess diff detected

### ISSUE THREAD

**Issue by domrin123** [Accenture/sfpowerkit#513]
**Describe the bug**
When a businessProcesses for an object has been added and I run sfpowerkit:project:diff, the command runs and generates a source folder, but when running sfdx force:source:deploy for the generated diff I get:

`An object 'Opportunity.Wholesale' of type RecordType was named in package.xml, but was not found in zipped directory`

This appears to be because while the "businessProcesses" folder has been populated with Wholesale.recordType-meta.xml, the "recordType" folder also needs Wholesale.recordType-meta.xml which doesn't appear to have been copied.

**To Reproduce**

1. sfdx sfpowerkit:project:diff --revisionfrom hashhere
--output diff

**Expected behavior**
Wholesale.recordType-meta.xml should be included in diff source

**Desktop (please complete the following information):**

- OS: Windows
- Node Version 12.16.1
- Version of sfpowerkit  2.8.7
- Salesforce Org Version [ In case of pre release window ] Spring '21

**Comment by genoud** [comment]
I was not able to reproduce this issue. Not sure if this is related to business process as they does not have dependency on Record Type. https://developer.salesforce.com/docs/atlas.en-us.230.0.api_meta.meta/api_meta/meta_businessprocess.htm.
@domrin123  can you provide the output of your diff command?

**Comment by domrin123** [comment]
Yeah I assumed it was to do with the businessProcess because if I remove the businessProcess, the deploy works ok. Likewise, if I include the relevant recordType, the deploy works ok too. I've attached the output for the diff.
[diff.txt](https://github.com/Accenture/sfpowerkit/files/6419733/diff.txt)

**Comment by domrin123** [comment]
Actually - apologies. I believe this error was thrown due a mismatch in the source in the org, whereby the recordType should already have existed. I'll close this. Thanks for looking into this.
