### ISSUE TITLE
Use stderr for logs

### ISSUE THREAD

**Issue by rody** [Accenture/sfpowerkit#515]
**Describe the bug**
Most of the commands uses stdout to display a command output and for logging.
This prevents parsing the output of a command as the logs are mixed with the output.

**To Reproduce**
for example:

`sfdx sfpowerkit:org:healthcheck | jq "."`

results in `parse error: Invalid numeric literal at line 1, column 13` because of this log on stdout: `Successfully Retrived Health Check Details` 

Using the `--json` flags remove the logs but add extra output.

`sfdx sfpowerkit:org:healthcheck`
results in the following output (notice the extra JSON object at the end):
```json 
{
  "highriskitems": [
    "Enable clickjack protection for customer Visualforce pages with standard headers",
    "Enable clickjack protection for customer Visualforce pages with headers disabled",
    "Require HttpOnly attribute",
    "Require a minimum 1 day password lifetime",
    "Enforce login IP ranges on every request",
    "Obscure secret answer for password resets",
    "Require identity verification for email address changes"
  ],
  "mediumriskitems": [
    "Maximum invalid login attempts",
    "Password complexity requirement",
    "Lockout effective period"
  ],
  "lowriskitems": [],
  "informationalriskitems": [],
  "score": "76"
}
{
  "status": 0,
  "result": true
}
```

**Expected behavior**
Command output should be written to stdout and log messages should be written to stderr.

**Desktop (please complete the following information):**

- OS: MacOs
- Node Version: v16.0.0

**Comment by rody** [comment]
related to https://github.com/oclif/cli-ux/issues/155

**Comment by rblancho-transurban** [comment]
for the `source:pmd` command, the fix is in https://github.com/Accenture/sfpowerkit/pull/516

**Comment by rody** [comment]
for the `source:pmd` command, the fix is in #516

**Comment by nabondance** [comment]
This issue also concern pool commands.
For example with `sfpowerkit:pool:create`:
![create json](https://user-images.githubusercontent.com/32196400/121338638-f9f8d180-c91d-11eb-85b1-574bb9dd7b7a.png)

It looks like the standard cli output is mixed with the plugin json output.

**Comment by rblancho-transurban** [comment]
@azlam-abdulsalam  can we keep this one open ?
