### ISSUE TITLE
Activity Custom Fields' permissions are incorrectly stripped out during reconcile

### ISSUE THREAD

**Issue by abhisheksaxena7** [Accenture/sfpowerkit#517]
**Describe the bug**
The profile reconcile command removes the permissions for Activity custom fields after running. I assume that's because in profile the permissions come with Task.customFieldName and Event.customFieldName but the actual custom fields reside in the Activity/fields folder instead of Task/fields and Event/fields.

**To Reproduce**

1. Have Activity Custom Fields in the repository(for ex: Activity.CustomFieldName). These custom fields would appear in the Activity/Fields folder.
2. The permission for these fields would be retrieved in the profile as Event.CustomFieldName and Task.CustomFieldName correctly through the profile retrieve command.
2. Run sfdx sfpowerkit:profile:reconcile -f force-app -s
3. Permissions for Task.CustomFieldName and Event.CustomFieldName are getting stripped.

**Expected behavior**
Task.CustomFieldName and Event.CustomFieldName permissions in the Profile are persisted.

**Desktop (please complete the following information):**

- OS: Windows
- Node Version
- Version of sfpowerkit[e.g 1.45.0] - 2.9.2

**Comment by azlam-abdulsalam** [comment]
This is fixed, available in alpha, will be part of next release
