### ISSUE TITLE
powerkit install package dependencies issue 

### ISSUE THREAD

**Issue by henry88lay** [Accenture/sfpowerkit#520]
issue occurring when run sfpowerkit:power:dependencies:install please investigate further.
WORKING ON ADDING MORE DETAIL.

**Comment by azlam-abdulsalam** [comment]
@henry88lay  would you be able to provide more details

**Comment by azlam-abdulsalam** [comment]
@henry88lay  I am closing this issue as it doesn't have enough details. Please feel free to reopen
