### ISSUE TITLE
Reconciling  ExternalDataSources failing

### ISSUE THREAD

**Issue by bmpandey** [Accenture/sfpowerkit#524]
sfpowerkit 2.9.2

INFO [2021-06-01 02:09:56.295 +0000] (sfpowerkit): Reconciling profile C:\tools\my_sf_project\CCM\src-access-mgmt\main\default\profiles\Business Administration.profile-meta.xml
DEBUG [2021-06-01 02:09:56.562 +0000] (sfpowerkit): Reconciling App
DEBUG [2021-06-01 02:09:56.780 +0000] (sfpowerkit): Application Visiblitilties reduced from 31  to  30
DEBUG [2021-06-01 02:09:56.781 +0000] (sfpowerkit): Reconciling Classes
DEBUG [2021-06-01 02:10:04.013 +0000] (sfpowerkit): Class Access reduced from 1316  to  1316
DEBUG [2021-06-01 02:10:04.013 +0000] (sfpowerkit): Reconciling Fields
DEBUG [2021-06-01 02:10:42.419 +0000] (sfpowerkit): Fields Level Permissions reduced from 6534  to  6511
DEBUG [2021-06-01 02:10:42.421 +0000] (sfpowerkit): Reconciling Objects
DEBUG [2021-06-01 02:10:43.011 +0000] (sfpowerkit): Object Permissions reduced from 318  to  315
DEBUG [2021-06-01 02:10:43.011 +0000] (sfpowerkit): Reconciling Pages
DEBUG [2021-06-01 02:10:43.305 +0000] (sfpowerkit): Page Access Permissions reduced from 165  to  165
DEBUG [2021-06-01 02:10:43.305 +0000] (sfpowerkit): Reconciling Layouts
DEBUG [2021-06-01 02:10:44.637 +0000] (sfpowerkit): Layout Assignnments reduced from 486  to  483
DEBUG [2021-06-01 02:10:44.637 +0000] (sfpowerkit): Reconciling Record Types
DEBUG [2021-06-01 02:10:44.651 +0000] (sfpowerkit): Record Type Visibilities reduced from 90  to  89
DEBUG [2021-06-01 02:10:44.651 +0000] (sfpowerkit): Reconciling  Tabs
DEBUG [2021-06-01 02:10:45.544 +0000] (sfpowerkit): Tab Visibilities reduced from 271  to  267
DEBUG [2021-06-01 02:10:45.545 +0000] (sfpowerkit): Reconciling  ExternalDataSources
ERROR [2021-06-01 02:10:45.672 +0000] (sfpowerkit): items.find is not a function
    TypeError: items.find is not a function

RROR [2021-06-01 02:10:45.678 +0000] (sfpowerkit): An error occured during profile reconcile. You can rerun the command after a moment.

doing the reconcile as am not able to validate the package against the new ly created target from the production:
Error  sdx_sourceDeploy_pkg_1622512967331/profiles/Audit.profile                                           Audit                                           Unknown user permission: ManageSandboxes

getting above error for all the profiles, 

Please advise

**Comment by azlam-abdulsalam** [comment]
@genoud  can you have a look at this one?
