### ISSUE TITLE
Sharing rule on ActiveScratchOrgs does not permit deletions

### ISSUE THREAD

**Issue by aly76** [Accenture/sfpowerkit#529]
Non-admin users can be given access to fetch scratch orgs by applying a sharing rule on the ScratchOrgInfo object. However,  a similar approach does not work for deleting scratch orgs because sharing rules on the ActiveScratchOrg object do not provide delete access.

We need a best solution for allowing non-admins to delete scratch orgs from a pool, locally on their command-line.

**Comment by LawrenceLoz** [comment]
Hi @aly76 and @azlam-abdulsalam, would a permission set with Modify All (inc. Delete) on the Scratch Orgs Info / Active Scratch Org objects address this? This could be assigned to non-admins without extending their permissions beyond scratch org related objects

**Comment by azlam-abdulsalam** [comment]
@LawrenceLoz Yes, it would solve it. However, need to work out if any security implications can arise out if it.

@FabienTaillon  @manisfdcsfdx  your opinions?

**Comment by aly76** [comment]
Yeah, a permission set would work, but the security implication being that they have ability to modify all scratch orgs - not just the ones created by the CI user.

**Comment by LawrenceLoz** [comment]
Yes that's right, technically they could authenticate to or modify the records for orgs outside the pool. If your aim is to isolate developers' access to specific pools then alternatively could change ownership of the Active Scratch Org record to the user on fetch. With delete perm on the object they should be able to delete that record (but not others they don't own)

**Comment by azlam-abdulsalam** [comment]
These are the scenarios that I could think of
- A pool getting dropped by a non admin user?
  - Could be added by additional confirmation prompts in pool:delete
- Developer license restrictions?
   -  @aly76  to confirm whether developer license has any restrictions on these objects from applying modify All
-  Changing the owner of the record?
  - @LawrenceLoz  dont we need trigger for this? I was thinking of to avoid the need for any code

**Comment by LawrenceLoz** [comment]
Hi @azlam-abdulsalam, to reassign the owner you could use either code or a record triggered flow, but you're right I think we'd need additional automation in the org (in the scratchorgpool package I suppose) to run without sharing as the user wouldn't have access to do this directly. We might also need a new field on ScratchOrgInfo to be set to the user the org is allocated to on fetch.

This approach wouldn't address your first scenario though of non-admins dropping a whole pool of non-allocated orgs.

For me the modify all approach is preferable for its simplicity - easy to explain that non-admins just need to be assigned a permission set which can be included in the scratchorgpool package. Permission set description can of course explain the effect and risks, and users who have concerns around this and are happy to live without delete capability for non-admins could use the sharing rule + public groups approach instead

**Comment by azlam-abdulsalam** [comment]
FYI everyone, developer license doesn't allow you to have modify all permission on ScratchorgInfo Object. so basically we keep it simple, if you're using standard license then probably a permset with ModifyAll, if not available use a pipeline to delete
