### ISSUE TITLE
SfdxAuthUrl not being set with clean install of pool package

### ISSUE THREAD

**Issue by msimonis** [Accenture/sfpowerkit#535]
**Describe the bug**
When generating scratch orgs, currently the SfdxAuthUrl is not getting set because of an early break inside of a loop.

**To Reproduce**

1. Install the latest version of the pool package into an org
2. Create a pool
3. Observe the SfdxAuthUrl is not set

**Expected behavior**
I would expect the SfdxAuthUrl to be set when generating scratch orgs in a pool.

**Additional context**
I am suspecting that the "Allocation Status" field was the most recent addition to the package / framework. Currently in scratchOrgUtils.checkForNewVersionCompatible, it is iterating over the describe field results, and does a break once it hits Allocation Status. The problem is that in the describe result, this is the first custom field in the list. So it skips over the SfdxAuthUrl field, which causes it to not be set when generating scratch orgs.

**Comment by azlam-abdulsalam** [comment]
@msimonis  Thanks for this.. weird how we were able to test it. Thanks for the fix!
