### ISSUE TITLE
sfdx sfpowerkit:source:pmd fails to save output file

### ISSUE THREAD

**Issue by DougMidgley** [Accenture/sfpowerkit#539]
**Describe the bug**
We noticed when running the command sfdx sfpowerkit:source:pmd that the pmd-output file was no longer being produced since the 28th June.
We managed to workaround using 
`sfdx sfpowerkit:source:pmd -d=src_delta --version=${env:PMDVERSION} --report=pmd-output `
but noticed that --report is deprecated for --reportfile, getting the error
`--report is deprecated and will be removed in a future version. User --reportfile instead`

Interesting this additional flag was not required when running locally.

**To Reproduce**
run command `sfdx sfpowerkit:source:pmd -d=src_delta --version=6.34.0 --report=pmd-output ` on ubuntu machine. where 

**Expected behavior**
pmd-output file created with errors (or empty)

**Screenshots**

**Desktop (please complete the following information):**

- Agent name: 'Azure Pipelines 4'
- Agent machine name: 'fv-az104-341'
- Current agent version: '2.188.3'
- Operating System:  Ubuntu 20.04.2 LTS
- Virtual Environment
- Environment: ubuntu-20.04
- Version: 20210614.1
- Node
- OS: [e.g. Windows/Linux]
- Node Version
- Version of sfpowerkit latest (3.1.4 at time of writing)
- Salesforce Org Version Summer 21

**Additional context**
https://github.com/Accenture/sfpowerkit#source-related-functionalities uses --report. --reportfile throws sfpowerkit error as not supported

**Comment by azlam-abdulsalam** [comment]
@rody Can you comment on this?

**Comment by azlam-abdulsalam** [comment]
@DougMidgley  can you refer to this issue for the changes undertaken

https://github.com/Accenture/sfpowerkit/issues/514

**Comment by rody** [comment]
We have aligned the options in the pmd command with the ones from PMD itself (hence the deprecated flags).
To restore the old behaviour, use the 'reportfile' flags and set it to pmd-output. You might also need to specify a format for the report.
(I don't have access to my computer at the moment, but feel free to ping me if you need more details)

**Comment by rody** [comment]
@azlam-abdulsalam can we add an entry in the FAQ describing the command line options needed to reproduce the legacy behaviour with the current flags?

**Comment by rody** [comment]
@DougMidgley Can we close the issue or do you need more infos?

**Comment by azlam-abdulsalam** [comment]
@Caitlyn-Mills  Can you create a FAQ with the changes
