### ISSUE TITLE
sfdx sfpowerkit:pool:fetch auto logon feature not working in combination  with --json parameter

### ISSUE THREAD

**Issue by stoevie** [Accenture/sfpowerkit#541]
When using sfdx sfpowerkit:pool:fetch --tag <poolname> --json command the output doesn't contain information
the authorization was successful and is also not executed.

**To Reproduce**

sfdx auth:sfdxurl:store -f user.json --setdefaultdevhubusername --setalias DevHub (login to devhub)
RESULT=$(sfdx sfpowerkit:pool:fetch --tag testpool --json)                                       (claim scratch org)
USERNAME=$(echo "$RESULT" | jq -r '.result.username')                                           (get scratch org username)
sfdx alias:set SO="$USERNAME"                                                                                 (set alias)
sfdx force:config:set defaultusername=SO                                                                 (set default)

error: ERROR running config:set: No AuthInfo found for name

**Expected behavior**
After claiming a scratch org, it is succesful authorized and the defaultusername is correctly set

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: v12.18.4
- Version of sfpowerkit : v3.1.5
- Salesforce Org Version : Summer21 release

**Additional context**
https://github.com/Accenture/sfpowerkit/discussions/530

**Comment by azlam-abdulsalam** [comment]
While using JSON, the autologin is currently disabled. You might have to use the details in the JSON and authenticate to the org using sfdx auth commands

I will have a look whether to improve it. 

@aly76

**Comment by azlam-abdulsalam** [comment]
Thaks @stoevie . We will be fixing this in the next release

**Comment by DougMidgley** [comment]
Any reason for doing this? Facing this limitation now makes it a real pain to handle errors which come back
