### ISSUE TITLE
Error Creating Pool with JWT Bearer Flow

### ISSUE THREAD

**Issue by msimonis** [Accenture/sfpowerkit#542]
**Describe the bug**
In a CI environment, when running the `sfpowerkit:pool:create` command after authorizing with the JWT Bearer Flow, you will see an error: "Unable to provision scratch org  1 . Due to following Error: undefined refreshToken". This is due to the fact that the JWT flow does not provide a refresh token.

**To Reproduce**

1. sfdx auth:jwt:grant -i ${client_id} -f ${key_file} -u ${devhub_username}
2. sfdx sfpowerkit:pool:create -f config/pool-config.json -v ${devhub_username}

**Expected behavior**
The pool should be created, and scratch orgs created in the pool, without error.

**Desktop (please complete the following information):**

- OS: Linux
- Node Version: 14.17.1
- Version of sfpowerkit: 3.1.5

**Additional context**
It appears the problem is this line of code: https://github.com/Accenture/sfpowerkit/blob/main/src/utils/scratchOrgUtils.ts#L199

Maybe wrapping in a try catch to handle any errors would be best, instead of halting the process of scratch org creation. It's also worth noting that the SfdxAuthUrl will not work with the JWT flow, because no refresh token is provided - unless I am missing something.

There was a change in the sfdx cli that now validates the existence of the refresh token, which might not have been the case when originally developed: https://github.com/forcedotcom/sfdx-core/pull/396

**Comment by azlam-abdulsalam** [comment]
Thanks @msimonis . We noticed this issue yesterday as we are refactoring pool code in sfpowerscripts. As  you mentioned it is about missing refresh token when using JWT.

 https://github.com/Accenture/sfpowerscripts/issues/540

Will be releasing a patch today.

**Comment by azlam-abdulsalam** [comment]
This is currently fixed in 3.1.6
