### ISSUE TITLE
Unable to generate apex test class list 

### ISSUE THREAD

**Issue by Aravindh04** [Accenture/sfpowerkit#546]
**Describe the bug**
Command to execute the apex test list runs into error during execution

**To Reproduce**
Open a salesforce project Repository
Run the command 
```sh
 sfdx sfpowerkit:source:apextest:list -p common/post --resultasstring
```

1. sfdx sfpowerkit:source:apextest:list -p common/post --resultasstring

**Expected behavior**
To list down the Apex test classes associated with the repository

**Screenshots**
![image](https://user-images.githubusercontent.com/42031270/126743532-028f800f-7132-43b8-af08-cc6f0b6be89d.png)

**Desktop (please complete the following information):**

- OS: macOs 11.4
- Node Version: 15.8
- Version of sfpowerkit[e.g 1.45.0]: 3.1.6
- Salesforce Org Version [ In case of pre release window ]: NA

**Additional context**
The command is of course in beta and I have seen it working in the past. Currently, it runs into an exception. Tried in different repo types

**Comment by azlam-abdulsalam** [comment]
@aly76  and @manisfdcsfdx  can you triage this one

**Comment by aly76** [comment]
Might be a bad dependency in the latest build. Would suggest releasing a patch of sfpowerkit and seeing if the issue persists.
