### ISSUE TITLE
Latest release not able to create scratch org pools 

### ISSUE THREAD

**Issue by Caitlyn-Mills** [Accenture/sfpowerkit#550]
**Describe the bug**
Scratch org pool unable to execute command. SO Pool config does not meet schema requirements 

**To Reproduce**
sfdx sfpowerkit:pool:create -f <path to so config file> 

**Expected behavior**
Pool should be created as previously 

**Screenshots**
![image](https://user-images.githubusercontent.com/63215232/127945388-13022e14-482f-428c-a112-16fddea37bed.png)

**Comment by azlam-abdulsalam** [comment]
Releasing a hotfix which will rollback the changes

**Comment by azlam-abdulsalam** [comment]
@henry88lay  please create another issue, as this was closed as part of the last release

**Comment by henry88lay** [comment]
I made changes to the JSON Schema aligned to the sample and the doc.

Tested the new code against the following cases:
`
{
  "pool": {
    "expiry": 1,
    "config_file_path": "config/project-scratch-def.json",
    "tag": "sfpowerkit",
    "relax_ip_ranges": [
      {
        "start": "49.0.0.0",
        "end": "49.255.255.255"
      },
      {
        "start": "42.0.0.0",
        "end": "42.255.255.255"
      }
    ],
    "max_allocation": 1
  }
}

`
