### ISSUE TITLE
Add Package Metadata Validation Logic as pre-step to sfpowerscripts:orchestrator:validate

### ISSUE THREAD

**Issue by vuha-acn** [Accenture/sfpowerkit#553]
**Describe the bug**
During package validation, ensure that the package contains valid metadata similar to the logic in sfpowerkit:package:valid.  Both the contents of the package for metadata as well as the sfdx-project.json file should be valid (eg. path of package is correct)  If there are errors, the validation should immediately fail before proceeding to validate against scratch org CI pools.  

**To Reproduce**
Create an unlocked package in your sfdx-project.json file with an incorrect path (eg. typo for framework vs. frameworks) and run validate command.

**Expected behavior**
Fail validation due to the sfdx-project.json file being incorrect.  If the sfdx-project.json is correct, and the metadata in the unlocked package is incorrect, fail the validation.

**Screenshots**

![image](https://user-images.githubusercontent.com/59901319/129315081-facbedea-fccf-41c7-bd09-782d1258e55c.png)

**Platform Details (please complete the following information):**
 - OS: MacOS
 - Version [e.g. CLI Version  eg: 1.6.6] - Latest
 - Salesforce CLI(sfdx cli) Version: 7.110.0
 - CI Platform: GitLabs

**Additional context**
Validation scope should take the scope of the entire sfdx-project.json file for all unlocked packages.

**Comment by vuha-acn** [comment]
@azlam-abdulsalam  - Any prioritization for this item for the next release?

**Comment by henry88lay** [comment]
@azlam-abdulsalam - where does this sit for priority going into the next release?

**Comment by azlam-abdulsalam** [comment]
@vuha-acn  @henry88lay  This will be closed here, and will be picked up in sfpowerscripts
