### ISSUE TITLE
sfpowerkit:pool:create hangs on scratch org creation

### ISSUE THREAD

**Issue by aly76** [Accenture/sfpowerkit#559]
**Describe the bug**
The underlying SFDX CLI command `force:org:create` is encountering socket timeout, and the command is not exiting.

https://github.com/forcedotcom/cli/issues/1149

**Expected behavior**
Scratch org is created successfully or times out after 6 minutes

**Comment by henry88lay** [comment]
Ran tests on sfpowerkit:pool:create to replicate issue 5 times, scratch org pool creation is working well.
