### ISSUE TITLE
Using sfdx sfpowerkit:source:apextest:list doesn't detect a test class

### ISSUE THREAD

**Issue by xpsp789** [Accenture/sfpowerkit#565]
**Describe the bug**
When we've used the command sfdx sfpowerkit:source:apextest:list its not recognizing a test class in the given path

**Expected behavior**
For the command to recognize the class as a test class and list it from a json file.

**Screenshots**
![image](https://user-images.githubusercontent.com/74693968/133175390-f38fd237-43f3-479b-9ac1-720f77f11325.png)
![image](https://user-images.githubusercontent.com/74693968/133176491-60f93c95-ac59-49e5-bf6b-e9b3258d0595.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Version of sfpowerkit v1.22.10
- SFDX CLI v115.1

**Additional context**
The test class was being recognized before by the command, but when there were changes added to the test class, it wasn't being recognized anymore by the command.

**Comment by azlam-abdulsalam** [comment]
@aly76  any updates on this?

**Comment by henry88lay** [comment]
Reached out to @xpsp789. 
Closing ticket as the issue has been resolved.
