### ISSUE TITLE
 sfpowerkit:project:diff  project package filter not working correctly

### ISSUE THREAD

**Issue by jacobpeterson2012** [Accenture/sfpowerkit#575]
**Describe the bug**

**_Given_** a project directory structure:
```
- sfdx-src
---env-src
-------dev
-------devops
```
and  sfdx-project.json package has the **sfdx-src/env-src/dev** path for a package 

**_When_**  a change is made in sfdx-src/env-src/**devops**

**_Then_** the package build is not excluding the change.

**To Reproduce**

1. create the above project structure
2. commit a change in the **devops** folder
3. run command `sfdx sfpowerkit:project:diff -r HEAD~1 -d powerkitdif` 

**Expected behavior**
No package diff to be built as the change is made in the devops path which is not a path in sfdx-project.json

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Node Version
- Version of sfpowerkit[e.g 1.45.0]  - 3.2.3
- Salesforce Org Version - NA

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@jacobpeterson2012  is sfdc-src in the project path as well?

**Comment by jacobpeterson2012** [comment]
@azlam-abdulsalam no it's not a project path.
