### ISSUE TITLE
Profile user permission not being pulled down correctly during retrieve 

### ISSUE THREAD

**Issue by MarcDBehr** [Accenture/sfpowerkit#577]
**Describe the bug**
Profile user permission not being pulled down correctly. Specifically the "EmailTemplateManagement" userPermissions 

**To Reproduce**

1. Using SOQL, look at the PermissionsEmailTemplateManagement value for a profile ```select id,name, PermissionsEmailTemplateManagement From Profile where PermissionsEmailTemplateManagement = true``` and ensure that the value is true
2. Retrieve one of the the profiles using the command ```sfdx sfpowerkit:source:profile:retrieve -f force-app/main/default/profiles/ -u org -n "someprofile"```
3. Look in the download profile at the user permissions "EmailTemplateManagement"

```
    <userPermissions>
        <enabled>false</enabled>
        <name>EmailTemplateManagement</name>
    </userPermissions>
```

**Expected behavior**
The value for the setting is correct when the profile is retrieved

**Desktop (please complete the following information):**

- OS: MacOS 11.6
- Node Version v16.1.0
- Version of sfpowerkit[e.g 1.45.0] 3.2.2
- Salesforce Org Version [ In case of pre release window ] Summer'21 and WInter'22

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Thanks @MarcDBehr  for raising this. We are looking into it

**Comment by MarcDBehr** [comment]
2 other settings that don't seem to get pulled down correctly are:

- FlowUFLRequired
- EmailAdministration

All 3 of these userPermissions setting are not visible via the UI, but exist and have consequences if set improperly (I found out the hard way)

**Comment by azlam-abdulsalam** [comment]
Thanks @MarcDBehr. Interesting how we missed this so far

**Comment by genoud** [comment]
Hi @MarcDBehr

The goal behind the retrieve is to retrieve the whole configuration of profiles. But when we read the profile from Salesforce, only userPermissions set to true are returned. We wanted to have a complete view of profiles even userPermissions that are set to false. 
That's why we assumed that userPermissions available in an org and that are not returned when profiles are read should be set to false.
From what you just found, Salesforce does return userPermissions that are not visible from the  UI.
We need to figure out how to manage this.

I saw you comment on a post on Stackoverflow about the features impacted by some of those permissions and just wondering how this has never been raised.

Thanks

**Comment by genoud** [comment]
I'm just wondering why salesforce would hide some permissions on the UI and let them accessible and editable throw API.

**Comment by MarcDBehr** [comment]
Makes no sense to me either. I was burned by this this week. We used your program to retrieve the profiles from a sandbox and when they got pushed to production during a release, having the EmailTemplateManagement false causes all of our users (except admins)  to completely lose  access to all email templates. 2 days of headaches. I was able to see in the audit log that 3 permissions (these 3) were removed from users, but could not find them in the UI to fix the issue. And the name in the log does not match the name in the metadata, so that did not help either.

**Comment by azlam-abdulsalam** [comment]
Ah @MarcDBehr  sorry for that, Thanks for raising this.

**Comment by azlam-abdulsalam** [comment]
@genoud  Any idea, why we mark this as false? If its hidden in the UI, can we disregard it

**Comment by MarcDBehr** [comment]
something new that I noticed today... using 3.2.3, if I do a retrieve of the Admin profile, none of the userPermissions settings are being retrieved (and if there were any in the profile previously, they are gone after the retrieve command). It does not seem to be doing the same thing with other profiles, only the Admin one.... seems odd
