### ISSUE TITLE
After log in with 'sfpowerkit:auth:login' cannot create scratch org - 'client identifier invalid' error (works when log in via 'sfdx force:auth:web:login')

### ISSUE THREAD

**Issue by avesolovksyy** [Accenture/sfpowerkit#588]
**Describe the bug**
We are getting an error **Error authenticating with auth code due to: client identifier invalid** when trying to create a scratch org with standard sfdx command. After days of digging we've finally figured out that error happens only when we are logging into dev hub via `sfpowerkit:auth:login` command. When using standard `sfdx force:auth:web:login` command to log in into dev hub, we are able to create scratch org without any problem. After inspecting ~/.sfdx/mydevhubuser@domain.com.json file we noticed presence of additional property there when logging via standard sfdx web flow, and that is `"clientId": "PlatformCLI"`. Not sure exactly what it means, but when we added it manually into json prop file (exactly like that, i.e. with PlatformCLI value) representing dev hub org auth info after logging in via  `sfpowerkit:auth:login` we also were able to create scratch org successfully. Could you please modify `sfpowerkit:auth:login` command to save clientId property from connection object into authInfo so that we can avoid having such trouble.

**To Reproduce**

1. sfdx sfpowerkit:auth:login -a myDevHub -u "myUser@myDomain.com" -p "myPassword"
2. sfdx force:org:create -f config/basic.json -v myDevHub -s -d 1 -w 120 -a myTestScratchOrg

**Expected behavior**
Scratch org should be created successfully.

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version - v14.18.1
- Version of sfpowerkit - 3.3.2
- Salesforce Org Version - Winter 22, i.e. 53.0

**Additional context**
if we use `sfdx force:auth:web:login -a myDevHub` to log into the same dev hub, then we are able to create scratch org successfully on step 2.
Here is the json snippet describing dev hub auth info created into ~/.sfdx/ directory after successful log in via force:auth (pay attention to this part `"clientId": "PlatformCLI"`, that's what is missing in case of usng `sfpowerkit:auth:login`):
```
{
  "username": "myUser@myDomain.com",
  "accessToken": "...",
  "instanceUrl": "...",
  "orgId": "...",
  "loginUrl": "https://login.salesforce.com",
  "refreshToken": "...",
  "clientId": "PlatformCLI"
}
```
Not sure why, but it stars working when we manually update json structure by adding exactly this string `"clientId": "PlatformCLI"`. Please take a look how to fix it properly, so that we can continue using `sfpowerkit:auth` command.
Thanks in advance

**Comment by henry88lay** [comment]
@azlam-abdulsalam did further investigations on this ticket and looks like there are issues with `sfdx sfpowerkit:auth:login`

looks like we are having some issues on this command from the looks of things, already followed up with @aly76 but please advise best course of action going forward :)

`
sfdx sfpowerkit:auth:login -a testlogin -u "henry88lay@mindful-goat-akdfdu.com" -p "ENTERED_PASSWORD"
(node:14180) TypeError Plugin: @dxatscale/sfpowerscripts: Cannot read property 'setOptions' of undefined
module: @oclif/config@1.17.0
task: toCached
plugin: @dxatscale/sfpowerscripts
root: /Users/henry.lay/Documents/dx@scale/sfpowerscripts/packages/sfpowerscripts-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14180) TypeError Plugin: @dxatscale/sfpowerscripts: Cannot read property 'setOptions' of undefined
module: @oclif/config@1.17.0
task: toCached
plugin: @dxatscale/sfpowerscripts
root: /Users/henry.lay/Documents/dx@scale/sfpowerscripts/packages/sfpowerscripts-cli
See more details with DEBUG=*
 ›   Warning: sfdx-cli update available from 7.122.1 to 7.135.0.
-------------------------------------------------------------------------------------------
sfpowerkit  -- The DX@Scale Developer Toolkit -Version:4.1.3 -Release:February 22
-------------------------------------------------------------------------------------------
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
SfdxError: Unable to connect to the target org
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/src/commands/sfpowerkit/auth/login.ts:31:23
    at /Users/henry.lay/Documents/dx@scale/sfpowerkit/node_modules/jsforce/lib/promise.js:76:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  cause: undefined,
  actions: undefined,
  exitCode: 1
}
ERROR running sfpowerkit:auth:login:  INVALID_LOGIN: Invalid username, password, security token; or user locked out.
`

**Comment by Caitlyn-Mills** [comment]
Hey @avesolovksyy I just want to understand what the use case is around this. If you are just trying to create scratch orgs, do you need to login using the sfpowerkit command?

**Comment by Caitlyn-Mills** [comment]
Closing this as scratch orgs can be created with sfdx commands. Please reopen if you have any further information/justification.
