### ISSUE TITLE
sfpowerkit:package:dependencies:install Fails with syntax error

### ISSUE THREAD

**Issue by larspetterjohnsen** [Accenture/sfpowerkit#592]
**Describe the bug**
While running the command sfpowerkit:package:dependencies:install, the actual force:package:install command fails with message: ERROR running force:package:install:  core_1.ConfigAggregator.getValue is not a function
**To Reproduce**
sfpowerkit:package:dependencies:instal with a valdid XML

**Expected behavior**
Depenandicies are installed

**Screenshots**
![image](https://user-images.githubusercontent.com/63037386/139679981-5cad85d8-bd9d-4ff4-83f9-de348e553256.png)

**Desktop (please complete the following information):**

- OS: Windows
- Node Version:  v16.13.0
- Version of sfpowerkit 3.3.2
- Salesforce Org Version Winter '22 Patch 11.1

**Additional context**
Tried dowmngrading both SFpowerkit, og SFDX CLI, and with clean VS Code workspace

**Comment by azlam-abdulsalam** [comment]
This is quite weird. Did you had any errors during installation?

**Comment by larspetterjohnsen** [comment]
Hi. No no errors at all during installation

**Comment by larspetterjohnsen** [comment]
Bug was due to another plugin, rstk-sfdx-package-utils
