### ISSUE TITLE
sfpowerkit:pool:create does not default to 10 as specified in documentation.

### ISSUE THREAD

**Issue by 1ktribble** [Accenture/sfpowerkit#593]
**Describe the bug**
When using `sfpowerkit:pool:create` to create a scratch org pool, the creation script always creates the amount specified in _max_allocation_ in the configuration file instead of "10" as specified in the documentation.

**To Reproduce**
1. set any amount larger than 10 as the max_allocation value in the configuration file.
2. Run the `sfpowerkit:pool:create` script without specifying a batch size.

**Expected behavior**
When using `sfpowerkit:pool:create` to create a scratch org pool, the creation script should default to creating only 10 scratch orgs at a time as opposed to creating the value specified in _max_allocation_.

**Screenshots**
<img width="607" alt="Screen Shot 2021-11-02 at 8 57 33 AM" src="https://user-images.githubusercontent.com/7140983/139890642-bf26f5ac-e415-4b1f-98e6-6ccc409d4998.png">
<img width="224" alt="Screen Shot 2021-11-02 at 8 57 03 AM" src="https://user-images.githubusercontent.com/7140983/139890657-06578882-b3f8-4d96-84cc-c4dc3a3b2a25.png">
<img width="955" alt="Screen Shot 2021-11-02 at 8 56 34 AM" src="https://user-images.githubusercontent.com/7140983/139890663-93e02b98-08ba-4ff2-9198-9872a59d0759.png">

**Desktop (please complete the following information):**

- OS: Ubuntu-Latest
- Node Version: (version specified in dxatscale/sfpowerscripts container)
- Version of sfpowerkit[e.g 1.45.0]: 3.3.2
- Salesforce Org Version: Winter '22

**Comment by azlam-abdulsalam** [comment]
max_ allocation and batch size are different. One is the maximum amount of scratch orgs to be allocated, while the other how many should be built in parallel.

**Comment by henry88lay** [comment]
Hi @1ktribble 
Has this been resolved?

**Comment by 1ktribble** [comment]
> max_ allocation and batch size are different. One is the maximum amount of scratch orgs to be allocated, while the other how many should be built in parallel.

I understand they are different. Based on the documentation, I understood that to mean that there can be at most `max_allocation` in my dev hub of scratch orgs at a time, but `batch size` of scratch orgs created during the creation script run.

**Comment by nabondance** [comment]
Hi @1ktribble,
I had the same issue and thought the same thing about `batch size` but in fact it doesn't work like that.
I haven't found a way to limit the number of SO created during one script run. Maybe you can try to modify your `pool-def.json` dynamically.

The answer I got: 
https://github.com/Accenture/sfpowerkit/issues/461#issuecomment-763129178

**Comment by henry88lay** [comment]
Hi @1ktribble 
Just to make sure we are on the same page, you are looking to have `batch size` to help control the number of scratch orgs in a single batch?

I had a look into our docs and I can confirm you are able to control the batch size using the flag `-b` on the command.
<img width="1838" alt="Screen Shot 2021-12-08 at 9 15 54 am" src="https://user-images.githubusercontent.com/40649970/145115268-07d5b5d4-8b13-499e-aaea-510832c08652.png">

Let me know how it goes :)

**Comment by 1ktribble** [comment]
> Hi @1ktribble Just to make sure we are on the same page, you are looking to have `batch size` to help control the number of scratch orgs in a single batch?
> 
> I had a look into our docs and I can confirm you are able to control the batch size using the flag `-b` on the command. <img alt="Screen Shot 2021-12-08 at 9 15 54 am" width="1838" src="https://user-images.githubusercontent.com/40649970/145115268-07d5b5d4-8b13-499e-aaea-510832c08652.png">
> 
> Let me know how it goes :)

Hi @henry88lay, not quite on the same page. I want to make sure that each time I run the create script, a certain number of scratch orgs are created during the entirety of that script's run.

**Comment by Caitlyn-Mills** [comment]
Documentation has been updated to clarify batch size. Please submit a feature request if wanting to have a 'provision_amount' type feature added.
