### ISSUE TITLE
Bad XML format for packaging permissions when downloading profiles in new versions

### ISSUE THREAD

**Issue by jonathanwiesel** [Accenture/sfpowerkit#596]
**Describe the bug**
In new versions, for example 3.3.4, when retrieving profiles from a sandbox some packaging userPermissions are downloaded with bad format:

```xml
<userPermissions>
        <enabled/>
        <name>CreatePackaging</name>
</userPermissions>
```

**To Reproduce**

Install v3.3.4 and retrieve a custom profile

1. sfdx sfpowerkit:source:profile:retrieve

**Expected behavior**

```xml
<userPermissions>
        <enabled>false</enabled>
        <name>CreatePackaging</name>
</userPermissions>
```

**Desktop (please complete the following information):**

- OS: macOS 11.3
- Node Version v16.4.0
- Version of sfpowerkit v3.3.4
- Salesforce Org Version Winter '22

**Comment by azlam-abdulsalam** [comment]
@genoud  can you have a look into this?
