### ISSUE TITLE
Header doesnt get displayed in PMD commands.

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#601]
The `Pmd` class needs an explicitly defined `--loglevel` flag where the default level is set to INFO, otherwise the level is WARN which stops the header in `SfpowerkitCommand` from printing.

_Originally posted by @aly76 in https://github.com/Accenture/sfpowerkit/pull/598#discussion_r755675766_

**Comment by Caitlyn-Mills** [comment]
Issue not validated
