### ISSUE TITLE
package:valid --bypass flag is not respected

### ISSUE THREAD

**Issue by rubiatoEJ** [Accenture/sfpowerkit#607]
**Describe the bug**
When executing the `package:valid` with bypass flag it is not being respected
`sfdx sfpowerkit:package:valid -n <package_name> -b StandardValueSet`

An error will occur indicating:
`Unsupported metadata in package <package_name>`
Please see screenshot for more details.

**To Reproduce**

1. sfdx sfpowerkit:<module>:<command> <options>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/88638065/145928985-f78abc5a-1dbb-4d45-8e46-fc1e86d24880.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows/Linux]
- Node Version
- Version:3.4.3 -Release:December 21
- Salesforce Org Version [ In case of pre release window ]

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Thanks @rubiatoEJ , missed the requirement of bypass in the PR merged yesterday. Looking into it
