### ISSUE TITLE
Add Alias to Pool Fetch documentation

### ISSUE THREAD

**Issue by DougMidgley** [Accenture/sfpowerkit#612]
**Describe the bug**
From the documentation it is not clear that -a will give the relevant alias to the retrieved scratch org

**To Reproduce**

1. sfdx sfpowerkit:pool:fetch -t test -v devhub -a fetchtest

**Expected behavior**
- Alias is provided via above command (works) but is not documented.

**Comment by henry88lay** [comment]
Hi @DougMidgley 

Thank you for your patience and for pointing that out. I have added the -a flag description to the documentation and created a branch for this fix :)
