### ISSUE TITLE
project:diff with multiple package directories

### ISSUE THREAD

**Issue by asifalikar** [Accenture/sfpowerkit#617]
**Describe the bug**
If the project has multiple package directories the sfdx-project.json generated by project:diff command does not contains all the package information which resulting in deploy error. 

**ERROR running force:source:deploy:  The sfdx-project.json file must include one, and only one, default package directory (path). Because your sfdx-project.json file contains only one package directory, it must be the default. Remove the '"default": false' key and try again.**

**To Reproduce**
- add a new package in sfdx-project.json {"path":"package1"} assuming force-app is the default one.
- add a new APEX class to package1/main/default/classes and commit
- now run the project:diff between the recent 2 git revisions
- check the generate sfdx-project.json. It will only have the package1 but it does not have the force-app. 

**Expected behavior**
the generated delta should contains the full copy of sfdx-project.json file not the delta.

**Desktop (please complete the following information):**

- OS: [e.g. Windows/Linux]: MacOS 12.0.1
- Node Version - v15.11.0
- Version of sfpowerkit[e.g 1.45.0] - 4.0.1

**Comment by azlam-abdulsalam** [comment]
@genoud  can you have a look into this?

**Comment by genoud** [comment]
Hi @asifalikar 

This does not seems to be a bug. The diff command copy the sfdx-project.json from the project and then remove any package directory for which there is no change captured by the command. 

Keeping all the package directories will just let run the deployment on the default package directory where there is no component to deploy. Meaning that if we copy the whole sfdx-project.json, you would not have that error but nothing will be deploy on your target environment.

When working with multiple package directories, you should plan the deployment for each of them. In this case, you should run the deployment  by specifying the package1 directory.

You can run a command on a specific package directory and you will have diff output with a sfdx-project.json generated to deploy that single package. (pushed a small fix though on this)

**Comment by azlam-abdulsalam** [comment]
Thanks @genoud. @henry88lay  can you take over this from a testing perspective and slate it for Feb Release

**Comment by henry88lay** [comment]
@azlam-abdulsalam @genoud ran the tests on that branch everything looks good to me
