### ISSUE TITLE
Validate package metadata is not supporting metadatatype "StandardValueSet"

### ISSUE THREAD

**Issue by sumanth-bolledla-acn** [Accenture/sfpowerkit#618]
**Describe the bug**
The command "sfdx sfpowerkit:package:valid" is not supporting the metadata type "StandardValueSet". The same worked fine in older versiona of sfpowerkit( e.g.,3.3.2), but is failing in v4.0.1 which is being used in the docker image pulled by the orchestrator.

**To Reproduce**

1. sfdx sfpowerkit:package:valid -n <package with StandardValueSet metadata type components>

**Expected behavior**
The Validation should succeed for the "StandardValueSet" components

**Screenshots**
<img width="381" alt="package_valid_command_failure" src="https://user-images.githubusercontent.com/92749436/149581286-f4ec1b8c-4dad-4c2f-a721-13fc8b2c3fe1.png">

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: 16.9.1
- Version of sfpowerkit: 4.0.1
- Salesforce Org Version: Winter22

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Please use the -b (bypass) flag option to bypass StandardValueSet as its not supported officially by Salesforce yet.
