### ISSUE TITLE
Profile reconciliation is failing in v4.1.3

### ISSUE THREAD

**Issue by sumanth-bolledla-acn** [Accenture/sfpowerkit#632]
**Describe the bug**
After updating the sfpowerkit to v4.1.3, the profile reconciliation is failing with "MODULE_NOT_FOUND" error.

**To Reproduce**
1. Install latest sfpowerkit version (4.1.3)
2. Run the below command
sfdx sfpowerkit:source:profile:reconcile -f {package nam} -u {Target Alias}

**Expected behavior**
Profile reconciliation should succeed without errors

**Screenshots**
<img width="712" alt="sfpowerkit-4 1 3" src="https://user-images.githubusercontent.com/92749436/153245154-066a31f2-0982-4cae-a0ce-5d89506a6ea7.png">

**Desktop (please complete the following information):**

- OS: Windows
- Node Version: 16.9.1
- Version of sfpowerkit: 4.1.3
- SFDX-CLI version: 7.129.0
- Salesforce Org Version [ In case of pre release window ] Winter22

**Additional context**
Since the same sfpowerkit version is being used in the sfpowerscripts as well, all the pipeline deployments are failing if the access-mgmt package is being deployed
After updating the sfdx-cli to "7.136.2", there is a new error. Below is the screenshot
<img width="604" alt="sfpowerkit-4 1 3_pic2" src="https://user-images.githubusercontent.com/92749436/153260500-219494ce-45c8-4933-bed3-296acd6233a3.png">

The "retrieve" command also seems to be impacted
<img width="586" alt="sfpowerkit-4 1 3_pic3" src="https://user-images.githubusercontent.com/92749436/153267639-f6615186-3931-4fee-a0f9-d98e415f54a3.png">

**Comment by vuha-acn** [comment]
@genoud  - Can you confirm if you are having any issues with the latest 4.1.3 release? @sumanth-bolledla-acn - Can you add the new screenshot errors after you have upgraded the CLI to match the docker container of sfdx-cli/7.136.2 darwin-x64 node-v16.11.1

**Comment by sumanth-bolledla-acn** [comment]
I have updated the description with the new screenshot @vuha-acn .

**Comment by marc-howard-ovo** [comment]
I'm also experiencing this issue

- OS: Big Sur MacOS
- node-v14.17.4
- sfpowerkit 4.1.3
- sfdx-cli/7.136.2

`ERROR running sfpowerkit:source:profile:reconcile:  Could not locate the bindings file. Tried:
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/build/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/build/Debug/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/build/Release/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/out/Debug/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/Debug/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/out/Release/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/Release/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/build/default/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/compiled/14.17.4/darwin/x64/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/addon-build/release/install-root/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/addon-build/debug/install-root/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/addon-build/default/install-root/better_sqlite3.node
 → /Users/marchoward/Documents/GitHub/crm-salesforce-orion/node_modules/@salesforce/lazy-require/lib/binding/node-v83-darwin-x64/better_sqlite3.node
error Command failed with exit code 1.`

**Comment by azlam-abdulsalam** [comment]
Apologies everyone! Please rollback to 4.0.3 while we are fixing this.

@sumanth-bolledla-acn  dx@scale docker image is rolled back to 4.0.3

**Comment by sumanth-bolledla-acn** [comment]
Thank you @azlam-abdulsalam , I can confirm the deployment pipelines are working fine now.

**Comment by azlam-abdulsalam** [comment]
This is now fixed in 4.1.4 and undergoing testing

**Comment by azlam-abdulsalam** [comment]
Its now fixed in 4.1.4
