### ISSUE TITLE
Reconcile fails in GitLab runners with database lock issue

### ISSUE THREAD

**Issue by sumanth-bolledla-acn** [Accenture/sfpowerkit#635]
**Describe the bug**
With the new sfpowerkit version(4.1.4) in the docker image for pipelines, the profile reconciliation is breaking due to database lock issue in GitLab shared runners. This is only observed in the GitLab shared runners, and I cannot reproduce the behavior in the local machine.

**To Reproduce**
1) Setup the orchestrator pipeline (which uses latest Docker image for sfpowerscripts) in GitLab
2) Deploy the access-mgmt package to any sandbox using the pipelines
3) The reconciliation breaks with data-base lock issue

Command:  sfdx sfpowerkit:source:profile:reconcile

**Expected behavior**
The behavior of reconciliation should be same when run in local machine or cloud runners(using docker)

**Screenshots**
<img width="672" alt="sfpowerkit-4 1 4_pic1" src="https://user-images.githubusercontent.com/92749436/153465070-c673b6ab-fceb-42de-86e0-e1194a5b4f96.png">
There are a total of 41 profiles in queue for reconciliation, split into 4 workers. When the reconcile errored out in each worker, it stopped processing reconciliation for all the remaining profiles in the queue of that worker, resulting in deployment failures.

**Desktop (please complete the following information):**

- OS: Linux[GitLab.com shared runners]
- Node Version: latest
- Version of sfpowerkit: 4.1.4
- Salesforce Org Version [ In case of pre release window ]

**Additional context**
I have tried several times on my local machine to reproduce the error, but local machine works fine. This seems like the issue is more related to the runners on GitLab. Not sure if the same is happening across other cloud runners.

**Comment by azlam-abdulsalam** [comment]
This is fixed in 4.1.5 and currently undergoing testing.
