### ISSUE TITLE
Sandbox Refresh command to support addtional options

### ISSUE THREAD

**Issue by azlam-abdulsalam** [Accenture/sfpowerkit#640]
During the refresh process for FULL sandboxes, using the Salesforce Web, we have some check boxes. The default screen is as: ![image](https://user-images.githubusercontent.com/49764558/150800026-9f4f4e66-8625-4c44-a1fd-ad7e7c66ddd6.png)

- Include field tracking history data (unchecked)
- include chatter data (unchecked)

- auto activate (checked)
- apex class (form empty)

We don't have those options as parameters for `sfpowerkit:org:sandbox:refresh`, so I'd like to ask: how's this command behave regarding those parameters? It uses the default, as mentioned above? Please advise if otherwise.

Another question: any plans for adding the option for run an Apex Class after Sadbox creation?
Something like we have for `sfdx force:org:create -t sandbox ApexClassId=myClass -u prodOrg -a MyFullSandbox -w 30`.

Thanks in advance

_Originally posted by @yurifugi in https://github.com/Accenture/sfpowerkit/discussions/624_

**Comment by Caitlyn-Mills** [comment]
@azlam-abdulsalam  can we close this?
