### ISSUE TITLE
Remove Requirement for MetadataAPI access

### ISSUE THREAD

**Issue by yippie** [Accenture/sfpowerkit#642]
**Is your feature request related to a problem? Please describe.**
We would like to use scratch org pooling using a user with "Salesforce Limited Access - Free" that is provided to ISVs for DX development.

Using the scratch org pooling feature currently does a check to make sure DevHub is configured correctly that requires the MetadataAPI (outlined in issue 531 https://github.com/Accenture/sfpowerkit/issues/531 ) . This requires that A) the user has permission to modify metadata even though there is no need for them to and b) must be a full enterprise license.

**Describe the solution you'd like**
Make the check optional or even better, remove it completly. Checking for a field existence is wasteful to be done every time as it is one time setup and attempts to use the field will also throw a pretty clear error of the same issue.

Requiring MetadataAPI access for the CI user needlessly opens a security hole as that is a very powerful permission granted to a user that is inherently not traceable to individuals and is shared (even if by only a few CI admins). Best practice is always to grant the least permissions possible, even in automated users as automated users can still be tricked or hijacked. Current system forces a violation of this principal.

**Describe alternatives you've considered**
Do the check in a way that doesn't require MetadatAPI access such as a simple soql query which would also check for lack of FLS (something that I assume is ALSO necessary for the pooling to work).

**Comment by azlam-abdulsalam** [comment]
Thanks @yippie , Will be addressing this

**Comment by azlam-abdulsalam** [comment]
@manisfdcsfdx  Can you look into this?
