### ISSUE TITLE
echo 'y' | sfdx plugins:install sfpowerkit fails in non root docker container

### ISSUE THREAD

**Issue by fedorzajac** [Accenture/sfpowerkit#645]
**Describe the bug**
sfpowerkit fails to install in container, few days ago it worked fine. no changes were made, container was just redeployed.

**command**
`echo 'y' | sfdx plugins:install sfpowerkit`

**Error Log from cloud**
stderr F You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements. 
Mar 3 05:37:26 us-south1-dev -test stderr F 
Mar 3 05:37:26 us-south1-dev -test stderr P This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: 
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit...
Mar 3 05:37:26 us-south1-dev -test stderr P  yarn add v1.22.10
Mar 3 05:37:26 us-south1-dev -test stderr F 
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... info No lockfile found.
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... [1/4] Resolving packages...
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... [2/4] Fetching packages...
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... [3/4] Linking dependencies...
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... [4/4] Building fresh packages...
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Mar 3 05:37:26 us-south1-dev -test stderr P Installing plugin sfpowerkit... failed
Mar 3 05:37:26 us-south1-dev -test stderr F 
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > cli-ux@5.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > request > har-validator@5.1.5: this library is no longer supported
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning sfpowerkit > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
Mar 3 05:37:26 us-south1-dev -test warning stderr F warning "sfpowerkit > @salesforce/command > @oclif/command@1.8.16" has unmet peer dependency "@oclif/config@^1".
Mar 3 05:37:26 us-south1-dev sfdevops-test error stderr F error /.local/share/sfdx/node_modules/better-sqlite3: Command failed.
Mar 3 05:37:26 us-south1-dev -test stderr F Exit code: 127
Mar 3 05:37:26 us-south1-dev -test stderr F Command: prebuild-install || npm run build-release
Mar 3 05:37:26 us-south1-dev -test stderr F Arguments: 
Mar 3 05:37:26 us-south1-dev -test stderr F Directory: /.local/share/sfdx/node_modules/better-sqlite3
Mar 3 05:37:26 us-south1-dev -test stderr F Output:
Mar 3 05:37:26 us-south1-dev -test stderr F prebuild-install WARN install EACCES: permission denied, mkdir '/.npm'
Mar 3 05:37:26 us-south1-dev -test stderr F /bin/sh: 1: npm: not found
Mar 3 05:37:26 us-south1-dev -test Error stderr F     Error: yarn add sfpowerkit@latest --non-interactive 
Mar 3 05:37:26 us-south1-dev -test stderr F     --mutex=file:/.local/share/sfdx/yarn.lock 
Mar 3 05:37:26 us-south1-dev -test stderr F     --preferred-cache-folder=/.cache/sfdx/yarn --check-files exited with code 
Mar 3 05:37:26 us-south1-dev -test stderr F     127
Mar 3 05:37:26 us-south1-dev -test stdout F Finished digital signature check. 

Please advise no how to proceed or how to lock specific previous working version in the installation command. Thank you.

**Comment by fedorzajac** [comment]
@azlam-abdulsalam, thank you, when I locked installation to previous version, it is working fine. `echo 'y' | sfdx plugins:install sfpowerkit@4.1.3` However, I still get some warnings that some packages are no longer supported
```bash
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements. 

This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Installing plugin sfpowerkit... yarn add v1.22.10
Installing plugin sfpowerkit... info No lockfile found.Installing plugin sfpowerkit... [1/4] Resolving packages...Installing plugin sfpowerkit... [2/4] Fetching packages...Installing plugin sfpowerkit... [3/4] Linking dependencies...Installing plugin sfpowerkit... [4/4] Building fresh packages...Installing plugin sfpowerkit... success Saved lockfile.Installing plugin sfpowerkit... success Saved 318 new dependencies.Installing plugin sfpowerkit... info Direct dependenciesInstalling plugin sfpowerkit... └─ sfpowerkit@4.1.3Installing plugin sfpowerkit... info All dependenciesInstalling plugin sfpowerkit... ├─ @kwsites/file-exists@1.1.1Installing plugin sfpowerkit... ├─ antlr4ts@0.5.0-alpha.4Installing plugin sfpowerkit... ├─ bcrypt-pbkdf@1.0.2Installing plugin sfpowerkit... ├─ caseless@0.12.0Installing plugin sfpowerkit... ├─ concat-map@0.0.1Installing plugin sfpowerkit... ├─ delayed-stream@1.0.0Installing plugin sfpowerkit... ├─ extsprintf@1.3.0Installing plugin sfpowerkit... ├─ fs.realpath@1.0.0Installing plugin sfpowerkit... ├─ http-signature@1.2.0Installing plugin sfpowerkit... ├─ lodash.get@4.4.2Installing plugin sfpowerkit... ├─ ncp@2.0.0Installing plugin sfpowerkit... ├─ process-nextick-args@2.0.1Installing plugin sfpowerkit... ├─ set-blocking@2.0.0Installing plugin sfpowerkit... ├─ tar-fs@2.1.1Installing plugin sfpowerkit... ├─ xmlcreate@2.0.4Installing plugin sfpowerkit... └─ zip-stream@4.1.0Installing plugin sfpowerkit... Done in 39.23s.Installing plugin sfpowerkit... installed v4.1.3
warning sfpowerkit > cli-ux@5.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning sfpowerkit > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfpowerkit > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning sfpowerkit > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning sfpowerkit > request > har-validator@5.1.5: this library is no longer supported
warning sfpowerkit > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning sfpowerkit > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning "sfpowerkit > cli-ux > @oclif/command@1.8.16" has unmet peer dependency "@oclif/config@^1".
Finished digital signature check.```

**Comment by azlam-abdulsalam** [comment]
@fedorzajac  You can ignore these, these are part of salesforce libs

**Comment by henry88lay** [comment]
@fedorzajac looks like things are resolved from your end can i close this ticket?

**Comment by peter-caitens** [comment]
I am having the same issue as the initial poster. When trying to rebuild my docker image it now fails when trying to install sfpowerkit. I get the following in the log.

```
#9 [5/5] RUN echo y | sfdx plugins:install sfpowerkit
#9 3.464 This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
#9 3.467 Installing plugin sfpowerkit... yarn add v1.22.18
#9 4.430 Installing plugin sfpowerkit... [1/4] Resolving packages...Installing plugin sfpowerkit... [2/4] Fetching packages...Installing plugin sfpowerkit... [3/4] Linking dependencies...Installing plugin sfpowerkit... [4/4] Building fresh packages...Installing plugin sfpowerkit... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin sfpowerkit... failed
#9 15.00 warning sfpowerkit > cli-ux@5.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#9 15.00 warning sfpowerkit > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#9 15.00 warning sfpowerkit > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
#9 15.00 warning sfpowerkit > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#9 15.00 warning "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
#9 15.00 error /root/.local/share/sfdx/node_modules/better-sqlite3: Command failed.
#9 15.00 Exit code: 1
#9 15.00 Command: prebuild-install || npm run build-release
#9 15.00 Arguments: 
#9 15.00 Directory: /root/.local/share/sfdx/node_modules/better-sqlite3
#9 15.00 Output:
#9 15.00 prebuild-install WARN install No prebuilt binaries found (target=17.8.0 runtime=node arch=x64 libc=musl platform=linux)
#9 15.00 
#9 15.00 > better-sqlite3@7.5.0 build-release
#9 15.00 > node-gyp rebuild --release
#9 15.00 
#9 15.00 gyp info it worked if it ends with ok
#9 15.00 gyp info using node-gyp@8.3.0
#9 15.00 gyp info using node@17.8.0 | linux | x64
#9 15.00 gyp ERR! find Python 
#9 15.00 gyp ERR! find Python checking Python explicitly set from command line or npm configuration
#9 15.00 gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
#9 15.00 gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
#9 15.00 gyp ERR! find Python Python is not set from environment variable PYTHON
#9 15.00 gyp ERR! find Python checking if "python3" can be used
#9 15.00 gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 15.00 gyp ERR! find Python checking if "python" can be used
#9 15.00 gyp ERR! find Python - "python" is not in PATH or produced an error
#9 15.00 gyp ERR! find Python 
#9 15.00 gyp ERR! find Python **********************************************************
#9 15.00 gyp ERR! find Python You need to install the latest version of Python.
#9 15.00 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 15.00 gyp ERR! find Python you can try one of the following options:
#9 15.00 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 15.00 gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 15.00 gyp ERR! find Python - Set the environment variable PYTHON
#9 15.00 gyp ERR! find Python - Set the npm configuration variable python:
#9 15.00 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 15.00 gyp ERR! find Python For more information consult the documentation at:
#9 15.00 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 15.00 gyp ERR! find Python **********************************************************
#9 15.00 gyp ERR! find Python 
#9 15.00 gyp ERR! configure error 
#9 15.00 gyp ERR! stack Error: Could not find any Python installation to use
#9 15.00 gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#9 15.00 gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#9 15.00 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#9 15.00 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#9 15.00 gyp ERR! stack     at exithandler (node:child_process:406:5)
#9 15.00 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#9 15.00 gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
#9 15.00 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#9 15.00 gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
#9 15.00 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#9 15.00 gyp ERR! System Linux 5.11.0-1028-azure
#9 15.00 gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
#9 15.00 gyp ERR! cwd /root/.local/share/sfdx/node_modules/better-sqlite3
#9 15.00 gyp ERR! node -v v17.8.0
#9 15.00 gyp ERR! node-gyp -v v8.3.0
#9 15.00 gyp ERR! not ok
#9 15.02     Error: yarn add sfpowerkit@latest --non-interactive 
#9 15.02     --mutex=file:/root/.local/share/sfdx/yarn.lock 
#9 15.02     --preferred-cache-folder=/root/.cache/sfdx/yarn --check-files exited with 
#9 15.02     code 1
#9 ERROR: process "/bin/sh -c echo y | sfdx plugins:install sfpowerkit" did not complete successfully: exit code: 1
```

This is the build script for my image
```
# use small node image
FROM azul/zulu-openjdk-alpine
grep sed tree
RUN apk add --update --no-cache git sed grep tree bash npm
RUN npm install sfdx-cli --global
RUN echo y | sfdx plugins:install sfdx-git-delta
RUN echo y | sfdx plugins:install sfpowerkit
```

Are you able to assist with making sure the install will work?

**Comment by azlam-abdulsalam** [comment]
Please refer to the docker file here. It needs Python, g++ and make as node-gyp triggers a compilation for c++ modules

https://github.com/Accenture/sfpowerscripts/blob/develop/dockerfiles/sfpowerscripts.Dockerfile

**Comment by azlam-abdulsalam** [comment]
Closing this due to no further updates
