### ISSUE TITLE
Re-auth to existing scratch org from dev pool via command

### ISSUE THREAD

**Issue by Schuchie** [Accenture/sfpowerkit#652]
**Is your feature request related to a problem? Please describe.**
I'm currently building a CI-Pipeline based on your CI-Template for Github. 
My company has a lot of SF admins who only work through the GitHub interface. We already have a GitHub action to fetch a DEV scratch org from the DEV pool (was more than easy with your tool). Now I would like to pull the made changes from this scratch org via the CI. Here I have the question, how to connect via sfpowerkit or via sfpowerscripts best with the Dev-Pool-Scratch-Org again (sfdx auth). To then fetch the changes via "sfdx force:source:pull".
I saw that you could theoretically connect to the org via username and pw with "sfdx sfpowerkit:auth:login". 

**Describe the solution you'd like**
However, it would be nicer if you only specify the username and the tool can automatically connect to the org. Is this already possible? Because I think your tool should have already the needed access information from the devhub.

**Describe alternatives you've considered**
Using Username and Password via "sfdx sfpowerkit:auth:login".

**Comment by azlam-abdulsalam** [comment]
@Schuchie You could write a query that fetches from ScratchOrgInfo object the authURL, which then could be used to authenticate to the org

**Comment by azlam-abdulsalam** [comment]
Awesome thanks for the share @Schuchie .
