### ISSUE TITLE
sfpowerkit:source:profile:reconcile --source-only does not work with parallel workers

### ISSUE THREAD

**Issue by IamDrowsy** [Accenture/sfpowerkit#655]
**Describe the bug**
Source only mode for `sfpowerkit:source:profile:reconcile` should reconcile profiles based on the given source folder. However after switching to parallel workers (#629 ) this no longer works and the command clears all profiles.
This is mentioned in #637 but the PR only resolves the error and does not restore the previous behaviour.

**To Reproduce**

1. checkout a project with a some metadata that is listed in a profile
2. delete the metadata from the source folder
3. run `sfdx sfpowerkit:source:profile:reconcile -f ${sourcefolder} -s`

**Expected behavior**
All profiles should no longer contain the locally deleted metadata

**Actual behavior**
All profiles are fully cleared (expect name `loginIpRanges` and `custom`)

**Desktop:**

-   OS: Windows/gitBash
-   Node Version: 14.16.1
-   Version of sfpowerkit: 4.2.1

**Additional context**
Switching back to sfpowerkit 4.0.3 or commit 9c43f12e61abdb6d13ed6e2490d9d1e1f3664ae2 resolves the issue.

I looked a bit into it and it I think the problem is, that the workers do not fill the `METADATA_INFO` with the components from the source folder. 

Possible solutions I see:
* don't use the workers for source-only mode as there are no call outs and the speed up should be negligible.
* fill the `METADATA_INFO` with the local components for every worker.

I'm not sure which would be the better one, but I can try to look into one of them.

**Comment by azlam-abdulsalam** [comment]
Thanks for raising this, I will look into this
