### ISSUE TITLE
sfpowerkit:source:profile:retrieve - tabVisibilities missed when  visibility = Hidden

### ISSUE THREAD

**Issue by AndreyShestakovACN** [Accenture/sfpowerkit#668]
**Describe the bug**
When retrieving Profiles some of the tabs, that were set as Hidden in a source org, are missed on xml files.
Few examples, that had to be added manually to xml:
```xml
    <tabVisibilities>
        <tab>standard-News</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-OmniSupervisorLightning</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-FlowOrchestrationWorkItem</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>standard-DeleteEvent</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities>
```

**To Reproduce**
1. Go to Profile <custom_profile> -> Object Settings -> News
2. Click `Edit` and change **Tab Settings** to `Tab Hidden`
3. Click `Save`
4. Retieve the profile:
> sfdx sfpowerkit:source:profile:retrieve -f "path/to/profiles" -n "custom_profile" -u SourceOrgAlias
5. Open the profile xm l file and search for `<tab>standard-News</tab>`
6. Verify the <tabVisibilities> for the tab is not found 

**Expected behavior**
It's expected that tab visibilities updated in a source org are included in a Profile xml

**Screenshots**
News Tab set Hidden in a source org. Note, the tab doesn't have Object Permissions
![image](https://user-images.githubusercontent.com/92478032/165764229-7d636a31-0dbe-4576-b312-e0befac5c315.png)
![image](https://user-images.githubusercontent.com/92478032/165764589-863d5291-dd01-413f-ab43-137d39f49864.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Node Version [v16.14.2]
-   Version of sfpowerkit [4.2.5]
-   Salesforce Org Version [ API 54.0 ]

**Additional context**
We found all the tabs in question don't have **Object Permissions**, like News, Recycle Bin, etc.
We also ran the retrieve explicitly on API 53.0 and 54.0.
The issue looks somewhat similar to the old one described [here:](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profile.htm#profiletabvisibility_title)
![image](https://user-images.githubusercontent.com/92478032/165765999-75a5eb9a-0163-43dd-8adb-a0e6eb539c62.png)

**Comment by Caitlyn-Mills** [comment]
Thanks for raising the issue @AndreyShestakovACN. Can you let me know, have you used sfpowerkit with an earlier version without this issue occuring?

Thanks

**Comment by Caitlyn-Mills** [comment]
Thanks for the patience on this Issue. After doing some testing, I have found that the issue is actually with the way salesforce is retrieving the tab visibility. 
I have used the same scenario's with the sfdx force:source:retrieve command and have found the same results - the tab visibility is not found when set to hidden in the org. 

We will report this issue to SF and close the ticket.
