### ISSUE TITLE
sfdx sfpowerkit:source:profile:reconcile -s --folder .\force-app\ -n "PROFILE_NAME" removes incorrect permissions

### ISSUE THREAD

**Issue by RajaPaul** [Accenture/sfpowerkit#673]
The reconcile command is removing field permissions from the profile even though they are present in the repo.

example, it is removing permissions related to all custom fields in the Account Object and keeping only the standard permissions

the userpermissions are also getting removed.

I have been using the retrieve and reconcile for some time, this was never the behavior before. It seems the old releases are working correctly but the new release is breaking and reconciling the wrong permissions

**Comment by azlam-abdulsalam** [comment]
@RajaPaul  This is fixed in 4.2.6. it will be live next week
