### ISSUE TITLE
EISDIR error on sfpowerkit:project:diff command

### ISSUE THREAD

**Issue by swood09** [Accenture/sfpowerkit#87]
Getting `EISDIR: illegal operation on a directory, copyfile '.forceignore' -> '../temp'` when running `sfdx sfpowerkit:project:diff`
Directory structure is successfully created in ../temp but looks like it fails when attempting to copy over any files.

**Comment by azlam-abdulsalam** [comment]
Thanks for raising the issue. Could you provide details of the OS Details?

@genoud  Can you look into the issue

**Comment by manisfdcsfdx** [comment]
@swood09 is this happening when copying forceignore file?
can I get the OS details.

**Comment by azlam-abdulsalam** [comment]
@swood09  Alternatively can you provide an alternate directory to the destination and check?

**Comment by swood09** [comment]
@manisfdcsfdx the error indicates that it fails on the .forceignore file. No other files get copied into the directory structure. 
I am traveling so access my machine info. I know I’m running Mac OS 10.14.6 on my machine.... what other info should I get you? (Apologies... I am new to npm and SFDX)

**Comment by swood09** [comment]
@azlam-abdulsalam I did try another directory. Got the same error.

**Comment by azlam-abdulsalam** [comment]
Fixed in 1.18.3
