### ISSUE TITLE
project:diff shows changes between same commit

### ISSUE THREAD

**Issue by sfdcale** [Accenture/sfpowerkit#97]
<img width="1675" alt="Screen Shot 2019-09-16 at 9 59 17 PM" src="https://user-images.githubusercontent.com/11079913/65012990-2ceb6e00-d8ce-11e9-82e1-cd2c0c317cf5.png">

Sorry for lot of masking in the above screenshot. When I do the command `sfdx sfpowerkit:project:diff -d test -r HEAD -t HEAD` it shows output with bunch of components but it should no changes as I am comparing same commit with itself.

**Comment by azlam-abdulsalam** [comment]
Yep thats right, we will be throwing an error if we see the commit IDs are same

**Comment by swood09** [comment]
@sfdcale when you aren't specifying the same commit in to/from, is this command generating metadata files in the newly-created project directory?

**Comment by sfdcale** [comment]
@swood09 I just realized it was my mistake. I didn't delete the destination folder before running the command.
Because I didn't delete the destination folder, it still has components from previous execution of command. We can close this.

**Comment by sfdcale** [comment]
@swood09  When I don't specify revisionFrom and revisionTo parameters, I get this error :

> ERROR running sfpowerkit:project:diff:  Provide either diffFile or revisionFrom parameters

Yes, I am seeing meta.xml files generated when I run the command with valid commits.

**Comment by sfdcale** [comment]
@azlam-abdulsalam  It was mistake from my side to not clear the destination folder before running the command. You can close this issue, not sure if you want this to be open for something else.

**Comment by genoud** [comment]
@sfdcale Yes, I noticed it and I pushed a fix to empty the destination folder when you run a command. And also throw an error message when one provide same commit.

**Comment by azlam-abdulsalam** [comment]
A temporary fix has been applied in 1.18.5, which produces an empty diff folder when the from and to commits are same. We have planned an message output in later sprint

**Comment by erick-bs** [comment]
Hi guys! I'm a new Salesforce Developer and I'm trying to solve this error, even though I have no problems with the CI/CD process, which means, that when I have new commits, the scheduled run the pipeline on GitHub with no errors, but when I don't have any commit to merge when the automatic process ran daily, shows up this error message. Is there any workaround to avoid this error and the pipeline pass with no error in this case?

Thank you very much, I really appreciate any help...

![image](https://user-images.githubusercontent.com/57912551/96449009-82522700-1214-11eb-9a61-e5211586f86f.png)

**Comment by azlam-abdulsalam** [comment]
@erick-bs  Couple of options here
- Change your ci/cd process from daily to producing a diff upon merge (have a look at sfpowerscripts  https://github.com/Accenture/sfpowerscriptsfor ci/cd plugin)
- write a small script which skips the diff if the revisions are same
